-- Provider Connect schema foundation (Portal 渠道商账号接入数据库基础).
-- Forward-only; no data backfill; existing rows keep NULL in every new
-- column and behave exactly as before.

-- 1) proxies.region: egress region label for future auto allocation.
--    NULL = unpartitioned node (excluded from auto allocation).
ALTER TABLE proxies ADD COLUMN IF NOT EXISTS region VARCHAR(20);
CREATE INDEX IF NOT EXISTS idx_proxies_region ON proxies (region);

-- 2) accounts.external_provider_account_id: Portal account reference
--    (pa_<uuid>). NULL for all non-portal accounts. Partial unique index:
--    one portal reference maps to at most one Sub2API account.
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS external_provider_account_id VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_external_provider_account_id
    ON accounts (external_provider_account_id)
    WHERE external_provider_account_id IS NOT NULL;

-- 3) provider_connect_sessions: durable record of a portal provider's
--    account authorization journey (table only in this phase; the OAuth
--    wiring arrives in a later phase).
CREATE TABLE IF NOT EXISTS provider_connect_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_provider_account_id VARCHAR(64) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    region VARCHAR(20),
    proxy_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    oauth_session_id VARCHAR(128),
    callback_url VARCHAR(512) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pcs_external_provider_account_id
    ON provider_connect_sessions (external_provider_account_id);
CREATE INDEX IF NOT EXISTS idx_pcs_status ON provider_connect_sessions (status);
CREATE INDEX IF NOT EXISTS idx_pcs_expires_at ON provider_connect_sessions (expires_at);
