-- Phase 21E-6E proxy-exclusive: exclusive proxy allocation for provider
-- accounts. Forward-only; additive; existing proxies/accounts untouched.
--
-- Model: one active allocation ties one proxy to one provider account
-- (external_provider_account_id). Two partial unique indexes enforce the
-- exclusivity invariant at the DB layer, so even under concurrency a proxy
-- can back at most one provider account and a provider account holds at most
-- one active allocation. Admin (non-portal) accounts do not use this table
-- and keep sharing proxies as before.
--
-- V1 uses a single active status 'assigned' (no separate reservation window):
-- credential validation is fast and Portal already caps batch size, so the
-- account is created and the allocation inserted together; concurrent claims
-- of the same free proxy collapse via the partial unique index. 'released'
-- is the terminal state when the account is removed and the proxy returns to
-- the pool.

CREATE TABLE IF NOT EXISTS proxy_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proxy_id BIGINT NOT NULL,
    external_provider_account_id VARCHAR(64) NOT NULL,
    account_id BIGINT,
    region VARCHAR(20),
    allocation_status VARCHAR(20) NOT NULL DEFAULT 'assigned',
    assigned_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    release_reason VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Exclusivity: at most one active (reserved/assigned) allocation per proxy.
CREATE UNIQUE INDEX IF NOT EXISTS uq_proxy_alloc_active_proxy
    ON proxy_allocations (proxy_id)
    WHERE allocation_status IN ('reserved', 'assigned');

-- Idempotency: at most one active allocation per provider account reference.
CREATE UNIQUE INDEX IF NOT EXISTS uq_proxy_alloc_active_external_ref
    ON proxy_allocations (external_provider_account_id)
    WHERE allocation_status IN ('reserved', 'assigned');

-- Capacity aggregation by region (available_slots = active proxies - active allocations).
CREATE INDEX IF NOT EXISTS idx_proxy_alloc_region_status
    ON proxy_allocations (region, allocation_status);
