// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/feedback"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// FeedbackUpdate is the builder for updating Feedback entities.
type FeedbackUpdate struct {
	config
	hooks    []Hook
	mutation *FeedbackMutation
}

// Where appends a list predicates to the FeedbackUpdate builder.
func (_u *FeedbackUpdate) Where(ps ...predicate.Feedback) *FeedbackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackUpdate) SetUserID(v int64) *FeedbackUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableUserID(v *int64) *FeedbackUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FeedbackUpdate) AddUserID(v int64) *FeedbackUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *FeedbackUpdate) SetType(v string) *FeedbackUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableType(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *FeedbackUpdate) SetContent(v string) *FeedbackUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableContent(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *FeedbackUpdate) SetRequestID(v string) *FeedbackUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableRequestID(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *FeedbackUpdate) ClearRequestID() *FeedbackUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FeedbackUpdate) SetStatus(v string) *FeedbackUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableStatus(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdminReply sets the "admin_reply" field.
func (_u *FeedbackUpdate) SetAdminReply(v string) *FeedbackUpdate {
	_u.mutation.SetAdminReply(v)
	return _u
}

// SetNillableAdminReply sets the "admin_reply" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableAdminReply(v *string) *FeedbackUpdate {
	if v != nil {
		_u.SetAdminReply(*v)
	}
	return _u
}

// ClearAdminReply clears the value of the "admin_reply" field.
func (_u *FeedbackUpdate) ClearAdminReply() *FeedbackUpdate {
	_u.mutation.ClearAdminReply()
	return _u
}

// SetRepliedAt sets the "replied_at" field.
func (_u *FeedbackUpdate) SetRepliedAt(v time.Time) *FeedbackUpdate {
	_u.mutation.SetRepliedAt(v)
	return _u
}

// SetNillableRepliedAt sets the "replied_at" field if the given value is not nil.
func (_u *FeedbackUpdate) SetNillableRepliedAt(v *time.Time) *FeedbackUpdate {
	if v != nil {
		_u.SetRepliedAt(*v)
	}
	return _u
}

// ClearRepliedAt clears the value of the "replied_at" field.
func (_u *FeedbackUpdate) ClearRepliedAt() *FeedbackUpdate {
	_u.mutation.ClearRepliedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackUpdate) SetUpdatedAt(v time.Time) *FeedbackUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeedbackMutation object of the builder.
func (_u *FeedbackUpdate) Mutation() *FeedbackMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeedbackUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeedbackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feedback.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := feedback.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Feedback.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := feedback.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Feedback.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := feedback.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "Feedback.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := feedback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Feedback.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedback.Table, feedback.Columns, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(feedback.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(feedback.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(feedback.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(feedback.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(feedback.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(feedback.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(feedback.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminReply(); ok {
		_spec.SetField(feedback.FieldAdminReply, field.TypeString, value)
	}
	if _u.mutation.AdminReplyCleared() {
		_spec.ClearField(feedback.FieldAdminReply, field.TypeString)
	}
	if value, ok := _u.mutation.RepliedAt(); ok {
		_spec.SetField(feedback.FieldRepliedAt, field.TypeTime, value)
	}
	if _u.mutation.RepliedAtCleared() {
		_spec.ClearField(feedback.FieldRepliedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedback.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeedbackUpdateOne is the builder for updating a single Feedback entity.
type FeedbackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeedbackMutation
}

// SetUserID sets the "user_id" field.
func (_u *FeedbackUpdateOne) SetUserID(v int64) *FeedbackUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableUserID(v *int64) *FeedbackUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FeedbackUpdateOne) AddUserID(v int64) *FeedbackUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *FeedbackUpdateOne) SetType(v string) *FeedbackUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableType(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *FeedbackUpdateOne) SetContent(v string) *FeedbackUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableContent(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *FeedbackUpdateOne) SetRequestID(v string) *FeedbackUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableRequestID(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *FeedbackUpdateOne) ClearRequestID() *FeedbackUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FeedbackUpdateOne) SetStatus(v string) *FeedbackUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableStatus(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAdminReply sets the "admin_reply" field.
func (_u *FeedbackUpdateOne) SetAdminReply(v string) *FeedbackUpdateOne {
	_u.mutation.SetAdminReply(v)
	return _u
}

// SetNillableAdminReply sets the "admin_reply" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableAdminReply(v *string) *FeedbackUpdateOne {
	if v != nil {
		_u.SetAdminReply(*v)
	}
	return _u
}

// ClearAdminReply clears the value of the "admin_reply" field.
func (_u *FeedbackUpdateOne) ClearAdminReply() *FeedbackUpdateOne {
	_u.mutation.ClearAdminReply()
	return _u
}

// SetRepliedAt sets the "replied_at" field.
func (_u *FeedbackUpdateOne) SetRepliedAt(v time.Time) *FeedbackUpdateOne {
	_u.mutation.SetRepliedAt(v)
	return _u
}

// SetNillableRepliedAt sets the "replied_at" field if the given value is not nil.
func (_u *FeedbackUpdateOne) SetNillableRepliedAt(v *time.Time) *FeedbackUpdateOne {
	if v != nil {
		_u.SetRepliedAt(*v)
	}
	return _u
}

// ClearRepliedAt clears the value of the "replied_at" field.
func (_u *FeedbackUpdateOne) ClearRepliedAt() *FeedbackUpdateOne {
	_u.mutation.ClearRepliedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackUpdateOne) SetUpdatedAt(v time.Time) *FeedbackUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeedbackMutation object of the builder.
func (_u *FeedbackUpdateOne) Mutation() *FeedbackMutation {
	return _u.mutation
}

// Where appends a list predicates to the FeedbackUpdate builder.
func (_u *FeedbackUpdateOne) Where(ps ...predicate.Feedback) *FeedbackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeedbackUpdateOne) Select(field string, fields ...string) *FeedbackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Feedback entity.
func (_u *FeedbackUpdateOne) Save(ctx context.Context) (*Feedback, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackUpdateOne) SaveX(ctx context.Context) *Feedback {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeedbackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feedback.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := feedback.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Feedback.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := feedback.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Feedback.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := feedback.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "Feedback.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := feedback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Feedback.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackUpdateOne) sqlSave(ctx context.Context) (_node *Feedback, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedback.Table, feedback.Columns, sqlgraph.NewFieldSpec(feedback.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Feedback.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedback.FieldID)
		for _, f := range fields {
			if !feedback.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feedback.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(feedback.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(feedback.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(feedback.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(feedback.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(feedback.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(feedback.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(feedback.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdminReply(); ok {
		_spec.SetField(feedback.FieldAdminReply, field.TypeString, value)
	}
	if _u.mutation.AdminReplyCleared() {
		_spec.ClearField(feedback.FieldAdminReply, field.TypeString)
	}
	if value, ok := _u.mutation.RepliedAt(); ok {
		_spec.SetField(feedback.FieldRepliedAt, field.TypeTime, value)
	}
	if _u.mutation.RepliedAtCleared() {
		_spec.ClearField(feedback.FieldRepliedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedback.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Feedback{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
