// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pricingmodel"
)

// PricingModelCreate is the builder for creating a PricingModel entity.
type PricingModelCreate struct {
	config
	mutation *PricingModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PricingModelCreate) SetCreatedAt(v time.Time) *PricingModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableCreatedAt(v *time.Time) *PricingModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PricingModelCreate) SetUpdatedAt(v time.Time) *PricingModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableUpdatedAt(v *time.Time) *PricingModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *PricingModelCreate) SetModel(v string) *PricingModelCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetModelType sets the "model_type" field.
func (_c *PricingModelCreate) SetModelType(v string) *PricingModelCreate {
	_c.mutation.SetModelType(v)
	return _c
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableModelType(v *string) *PricingModelCreate {
	if v != nil {
		_c.SetModelType(*v)
	}
	return _c
}

// SetUserType sets the "user_type" field.
func (_c *PricingModelCreate) SetUserType(v string) *PricingModelCreate {
	_c.mutation.SetUserType(v)
	return _c
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableUserType(v *string) *PricingModelCreate {
	if v != nil {
		_c.SetUserType(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PricingModelCreate) SetEnabled(v bool) *PricingModelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableEnabled(v *bool) *PricingModelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetInputPrice sets the "input_price" field.
func (_c *PricingModelCreate) SetInputPrice(v float64) *PricingModelCreate {
	_c.mutation.SetInputPrice(v)
	return _c
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableInputPrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetInputPrice(*v)
	}
	return _c
}

// SetOutputPrice sets the "output_price" field.
func (_c *PricingModelCreate) SetOutputPrice(v float64) *PricingModelCreate {
	_c.mutation.SetOutputPrice(v)
	return _c
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableOutputPrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetOutputPrice(*v)
	}
	return _c
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_c *PricingModelCreate) SetCacheReadPrice(v float64) *PricingModelCreate {
	_c.mutation.SetCacheReadPrice(v)
	return _c
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableCacheReadPrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetCacheReadPrice(*v)
	}
	return _c
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_c *PricingModelCreate) SetCacheWritePrice(v float64) *PricingModelCreate {
	_c.mutation.SetCacheWritePrice(v)
	return _c
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableCacheWritePrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetCacheWritePrice(*v)
	}
	return _c
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (_c *PricingModelCreate) SetOfficialInputPrice(v float64) *PricingModelCreate {
	_c.mutation.SetOfficialInputPrice(v)
	return _c
}

// SetNillableOfficialInputPrice sets the "official_input_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableOfficialInputPrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetOfficialInputPrice(*v)
	}
	return _c
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (_c *PricingModelCreate) SetOfficialOutputPrice(v float64) *PricingModelCreate {
	_c.mutation.SetOfficialOutputPrice(v)
	return _c
}

// SetNillableOfficialOutputPrice sets the "official_output_price" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableOfficialOutputPrice(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetOfficialOutputPrice(*v)
	}
	return _c
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (_c *PricingModelCreate) SetImagePricingJSON(v string) *PricingModelCreate {
	_c.mutation.SetImagePricingJSON(v)
	return _c
}

// SetNillableImagePricingJSON sets the "image_pricing_json" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableImagePricingJSON(v *string) *PricingModelCreate {
	if v != nil {
		_c.SetImagePricingJSON(*v)
	}
	return _c
}

// SetSavingPercent sets the "saving_percent" field.
func (_c *PricingModelCreate) SetSavingPercent(v float64) *PricingModelCreate {
	_c.mutation.SetSavingPercent(v)
	return _c
}

// SetNillableSavingPercent sets the "saving_percent" field if the given value is not nil.
func (_c *PricingModelCreate) SetNillableSavingPercent(v *float64) *PricingModelCreate {
	if v != nil {
		_c.SetSavingPercent(*v)
	}
	return _c
}

// Mutation returns the PricingModelMutation object of the builder.
func (_c *PricingModelCreate) Mutation() *PricingModelMutation {
	return _c.mutation
}

// Save creates the PricingModel in the database.
func (_c *PricingModelCreate) Save(ctx context.Context) (*PricingModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingModelCreate) SaveX(ctx context.Context) *PricingModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingModelCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pricingmodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pricingmodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ModelType(); !ok {
		v := pricingmodel.DefaultModelType
		_c.mutation.SetModelType(v)
	}
	if _, ok := _c.mutation.UserType(); !ok {
		v := pricingmodel.DefaultUserType
		_c.mutation.SetUserType(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := pricingmodel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SavingPercent(); !ok {
		v := pricingmodel.DefaultSavingPercent
		_c.mutation.SetSavingPercent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingModelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PricingModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PricingModel.updated_at"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "PricingModel.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := pricingmodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelType(); !ok {
		return &ValidationError{Name: "model_type", err: errors.New(`ent: missing required field "PricingModel.model_type"`)}
	}
	if v, ok := _c.mutation.ModelType(); ok {
		if err := pricingmodel.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserType(); !ok {
		return &ValidationError{Name: "user_type", err: errors.New(`ent: missing required field "PricingModel.user_type"`)}
	}
	if v, ok := _c.mutation.UserType(); ok {
		if err := pricingmodel.UserTypeValidator(v); err != nil {
			return &ValidationError{Name: "user_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.user_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PricingModel.enabled"`)}
	}
	if _, ok := _c.mutation.SavingPercent(); !ok {
		return &ValidationError{Name: "saving_percent", err: errors.New(`ent: missing required field "PricingModel.saving_percent"`)}
	}
	return nil
}

func (_c *PricingModelCreate) sqlSave(ctx context.Context) (*PricingModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingModelCreate) createSpec() (*PricingModel, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingmodel.Table, sqlgraph.NewFieldSpec(pricingmodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricingmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(pricingmodel.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.ModelType(); ok {
		_spec.SetField(pricingmodel.FieldModelType, field.TypeString, value)
		_node.ModelType = value
	}
	if value, ok := _c.mutation.UserType(); ok {
		_spec.SetField(pricingmodel.FieldUserType, field.TypeString, value)
		_node.UserType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(pricingmodel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.InputPrice(); ok {
		_spec.SetField(pricingmodel.FieldInputPrice, field.TypeFloat64, value)
		_node.InputPrice = &value
	}
	if value, ok := _c.mutation.OutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOutputPrice, field.TypeFloat64, value)
		_node.OutputPrice = &value
	}
	if value, ok := _c.mutation.CacheReadPrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64, value)
		_node.CacheReadPrice = &value
	}
	if value, ok := _c.mutation.CacheWritePrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64, value)
		_node.CacheWritePrice = &value
	}
	if value, ok := _c.mutation.OfficialInputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64, value)
		_node.OfficialInputPrice = &value
	}
	if value, ok := _c.mutation.OfficialOutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64, value)
		_node.OfficialOutputPrice = &value
	}
	if value, ok := _c.mutation.ImagePricingJSON(); ok {
		_spec.SetField(pricingmodel.FieldImagePricingJSON, field.TypeString, value)
		_node.ImagePricingJSON = &value
	}
	if value, ok := _c.mutation.SavingPercent(); ok {
		_spec.SetField(pricingmodel.FieldSavingPercent, field.TypeFloat64, value)
		_node.SavingPercent = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingModelCreate) OnConflict(opts ...sql.ConflictOption) *PricingModelUpsertOne {
	_c.conflict = opts
	return &PricingModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingModelCreate) OnConflictColumns(columns ...string) *PricingModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingModelUpsertOne{
		create: _c,
	}
}

type (
	// PricingModelUpsertOne is the builder for "upsert"-ing
	//  one PricingModel node.
	PricingModelUpsertOne struct {
		create *PricingModelCreate
	}

	// PricingModelUpsert is the "OnConflict" setter.
	PricingModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingModelUpsert) SetUpdatedAt(v time.Time) *PricingModelUpsert {
	u.Set(pricingmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateUpdatedAt() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldUpdatedAt)
	return u
}

// SetModel sets the "model" field.
func (u *PricingModelUpsert) SetModel(v string) *PricingModelUpsert {
	u.Set(pricingmodel.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateModel() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldModel)
	return u
}

// SetModelType sets the "model_type" field.
func (u *PricingModelUpsert) SetModelType(v string) *PricingModelUpsert {
	u.Set(pricingmodel.FieldModelType, v)
	return u
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateModelType() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldModelType)
	return u
}

// SetUserType sets the "user_type" field.
func (u *PricingModelUpsert) SetUserType(v string) *PricingModelUpsert {
	u.Set(pricingmodel.FieldUserType, v)
	return u
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateUserType() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldUserType)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PricingModelUpsert) SetEnabled(v bool) *PricingModelUpsert {
	u.Set(pricingmodel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateEnabled() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldEnabled)
	return u
}

// SetInputPrice sets the "input_price" field.
func (u *PricingModelUpsert) SetInputPrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldInputPrice, v)
	return u
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateInputPrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldInputPrice)
	return u
}

// AddInputPrice adds v to the "input_price" field.
func (u *PricingModelUpsert) AddInputPrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldInputPrice, v)
	return u
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PricingModelUpsert) ClearInputPrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldInputPrice)
	return u
}

// SetOutputPrice sets the "output_price" field.
func (u *PricingModelUpsert) SetOutputPrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldOutputPrice, v)
	return u
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateOutputPrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldOutputPrice)
	return u
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PricingModelUpsert) AddOutputPrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldOutputPrice, v)
	return u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PricingModelUpsert) ClearOutputPrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldOutputPrice)
	return u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PricingModelUpsert) SetCacheReadPrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldCacheReadPrice, v)
	return u
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateCacheReadPrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldCacheReadPrice)
	return u
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PricingModelUpsert) AddCacheReadPrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldCacheReadPrice, v)
	return u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PricingModelUpsert) ClearCacheReadPrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldCacheReadPrice)
	return u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PricingModelUpsert) SetCacheWritePrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldCacheWritePrice, v)
	return u
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateCacheWritePrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldCacheWritePrice)
	return u
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PricingModelUpsert) AddCacheWritePrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldCacheWritePrice, v)
	return u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PricingModelUpsert) ClearCacheWritePrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldCacheWritePrice)
	return u
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (u *PricingModelUpsert) SetOfficialInputPrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldOfficialInputPrice, v)
	return u
}

// UpdateOfficialInputPrice sets the "official_input_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateOfficialInputPrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldOfficialInputPrice)
	return u
}

// AddOfficialInputPrice adds v to the "official_input_price" field.
func (u *PricingModelUpsert) AddOfficialInputPrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldOfficialInputPrice, v)
	return u
}

// ClearOfficialInputPrice clears the value of the "official_input_price" field.
func (u *PricingModelUpsert) ClearOfficialInputPrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldOfficialInputPrice)
	return u
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (u *PricingModelUpsert) SetOfficialOutputPrice(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldOfficialOutputPrice, v)
	return u
}

// UpdateOfficialOutputPrice sets the "official_output_price" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateOfficialOutputPrice() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldOfficialOutputPrice)
	return u
}

// AddOfficialOutputPrice adds v to the "official_output_price" field.
func (u *PricingModelUpsert) AddOfficialOutputPrice(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldOfficialOutputPrice, v)
	return u
}

// ClearOfficialOutputPrice clears the value of the "official_output_price" field.
func (u *PricingModelUpsert) ClearOfficialOutputPrice() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldOfficialOutputPrice)
	return u
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (u *PricingModelUpsert) SetImagePricingJSON(v string) *PricingModelUpsert {
	u.Set(pricingmodel.FieldImagePricingJSON, v)
	return u
}

// UpdateImagePricingJSON sets the "image_pricing_json" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateImagePricingJSON() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldImagePricingJSON)
	return u
}

// ClearImagePricingJSON clears the value of the "image_pricing_json" field.
func (u *PricingModelUpsert) ClearImagePricingJSON() *PricingModelUpsert {
	u.SetNull(pricingmodel.FieldImagePricingJSON)
	return u
}

// SetSavingPercent sets the "saving_percent" field.
func (u *PricingModelUpsert) SetSavingPercent(v float64) *PricingModelUpsert {
	u.Set(pricingmodel.FieldSavingPercent, v)
	return u
}

// UpdateSavingPercent sets the "saving_percent" field to the value that was provided on create.
func (u *PricingModelUpsert) UpdateSavingPercent() *PricingModelUpsert {
	u.SetExcluded(pricingmodel.FieldSavingPercent)
	return u
}

// AddSavingPercent adds v to the "saving_percent" field.
func (u *PricingModelUpsert) AddSavingPercent(v float64) *PricingModelUpsert {
	u.Add(pricingmodel.FieldSavingPercent, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingModelUpsertOne) UpdateNewValues() *PricingModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricingmodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PricingModelUpsertOne) Ignore() *PricingModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingModelUpsertOne) DoNothing() *PricingModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingModelCreate.OnConflict
// documentation for more info.
func (u *PricingModelUpsertOne) Update(set func(*PricingModelUpsert)) *PricingModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingModelUpsertOne) SetUpdatedAt(v time.Time) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateUpdatedAt() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModel sets the "model" field.
func (u *PricingModelUpsertOne) SetModel(v string) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateModel() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateModel()
	})
}

// SetModelType sets the "model_type" field.
func (u *PricingModelUpsertOne) SetModelType(v string) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetModelType(v)
	})
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateModelType() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateModelType()
	})
}

// SetUserType sets the "user_type" field.
func (u *PricingModelUpsertOne) SetUserType(v string) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetUserType(v)
	})
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateUserType() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateUserType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingModelUpsertOne) SetEnabled(v bool) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateEnabled() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *PricingModelUpsertOne) SetInputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *PricingModelUpsertOne) AddInputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateInputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateInputPrice()
	})
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PricingModelUpsertOne) ClearInputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *PricingModelUpsertOne) SetOutputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PricingModelUpsertOne) AddOutputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateOutputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOutputPrice()
	})
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PricingModelUpsertOne) ClearOutputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOutputPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PricingModelUpsertOne) SetCacheReadPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PricingModelUpsertOne) AddCacheReadPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateCacheReadPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PricingModelUpsertOne) ClearCacheReadPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PricingModelUpsertOne) SetCacheWritePrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PricingModelUpsertOne) AddCacheWritePrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateCacheWritePrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PricingModelUpsertOne) ClearCacheWritePrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (u *PricingModelUpsertOne) SetOfficialInputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOfficialInputPrice(v)
	})
}

// AddOfficialInputPrice adds v to the "official_input_price" field.
func (u *PricingModelUpsertOne) AddOfficialInputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOfficialInputPrice(v)
	})
}

// UpdateOfficialInputPrice sets the "official_input_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateOfficialInputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOfficialInputPrice()
	})
}

// ClearOfficialInputPrice clears the value of the "official_input_price" field.
func (u *PricingModelUpsertOne) ClearOfficialInputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOfficialInputPrice()
	})
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (u *PricingModelUpsertOne) SetOfficialOutputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOfficialOutputPrice(v)
	})
}

// AddOfficialOutputPrice adds v to the "official_output_price" field.
func (u *PricingModelUpsertOne) AddOfficialOutputPrice(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOfficialOutputPrice(v)
	})
}

// UpdateOfficialOutputPrice sets the "official_output_price" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateOfficialOutputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOfficialOutputPrice()
	})
}

// ClearOfficialOutputPrice clears the value of the "official_output_price" field.
func (u *PricingModelUpsertOne) ClearOfficialOutputPrice() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOfficialOutputPrice()
	})
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (u *PricingModelUpsertOne) SetImagePricingJSON(v string) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetImagePricingJSON(v)
	})
}

// UpdateImagePricingJSON sets the "image_pricing_json" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateImagePricingJSON() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateImagePricingJSON()
	})
}

// ClearImagePricingJSON clears the value of the "image_pricing_json" field.
func (u *PricingModelUpsertOne) ClearImagePricingJSON() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearImagePricingJSON()
	})
}

// SetSavingPercent sets the "saving_percent" field.
func (u *PricingModelUpsertOne) SetSavingPercent(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetSavingPercent(v)
	})
}

// AddSavingPercent adds v to the "saving_percent" field.
func (u *PricingModelUpsertOne) AddSavingPercent(v float64) *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddSavingPercent(v)
	})
}

// UpdateSavingPercent sets the "saving_percent" field to the value that was provided on create.
func (u *PricingModelUpsertOne) UpdateSavingPercent() *PricingModelUpsertOne {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateSavingPercent()
	})
}

// Exec executes the query.
func (u *PricingModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PricingModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PricingModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PricingModelCreateBulk is the builder for creating many PricingModel entities in bulk.
type PricingModelCreateBulk struct {
	config
	err      error
	builders []*PricingModelCreate
	conflict []sql.ConflictOption
}

// Save creates the PricingModel entities in the database.
func (_c *PricingModelCreateBulk) Save(ctx context.Context) ([]*PricingModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingModelCreateBulk) SaveX(ctx context.Context) []*PricingModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *PricingModelUpsertBulk {
	_c.conflict = opts
	return &PricingModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingModelCreateBulk) OnConflictColumns(columns ...string) *PricingModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingModelUpsertBulk{
		create: _c,
	}
}

// PricingModelUpsertBulk is the builder for "upsert"-ing
// a bulk of PricingModel nodes.
type PricingModelUpsertBulk struct {
	create *PricingModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingModelUpsertBulk) UpdateNewValues() *PricingModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricingmodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PricingModelUpsertBulk) Ignore() *PricingModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingModelUpsertBulk) DoNothing() *PricingModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingModelCreateBulk.OnConflict
// documentation for more info.
func (u *PricingModelUpsertBulk) Update(set func(*PricingModelUpsert)) *PricingModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingModelUpsertBulk) SetUpdatedAt(v time.Time) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateUpdatedAt() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModel sets the "model" field.
func (u *PricingModelUpsertBulk) SetModel(v string) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateModel() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateModel()
	})
}

// SetModelType sets the "model_type" field.
func (u *PricingModelUpsertBulk) SetModelType(v string) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetModelType(v)
	})
}

// UpdateModelType sets the "model_type" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateModelType() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateModelType()
	})
}

// SetUserType sets the "user_type" field.
func (u *PricingModelUpsertBulk) SetUserType(v string) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetUserType(v)
	})
}

// UpdateUserType sets the "user_type" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateUserType() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateUserType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingModelUpsertBulk) SetEnabled(v bool) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateEnabled() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *PricingModelUpsertBulk) SetInputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *PricingModelUpsertBulk) AddInputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateInputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateInputPrice()
	})
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PricingModelUpsertBulk) ClearInputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *PricingModelUpsertBulk) SetOutputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PricingModelUpsertBulk) AddOutputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateOutputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOutputPrice()
	})
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PricingModelUpsertBulk) ClearOutputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOutputPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PricingModelUpsertBulk) SetCacheReadPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PricingModelUpsertBulk) AddCacheReadPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateCacheReadPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PricingModelUpsertBulk) ClearCacheReadPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PricingModelUpsertBulk) SetCacheWritePrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PricingModelUpsertBulk) AddCacheWritePrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateCacheWritePrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PricingModelUpsertBulk) ClearCacheWritePrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (u *PricingModelUpsertBulk) SetOfficialInputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOfficialInputPrice(v)
	})
}

// AddOfficialInputPrice adds v to the "official_input_price" field.
func (u *PricingModelUpsertBulk) AddOfficialInputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOfficialInputPrice(v)
	})
}

// UpdateOfficialInputPrice sets the "official_input_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateOfficialInputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOfficialInputPrice()
	})
}

// ClearOfficialInputPrice clears the value of the "official_input_price" field.
func (u *PricingModelUpsertBulk) ClearOfficialInputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOfficialInputPrice()
	})
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (u *PricingModelUpsertBulk) SetOfficialOutputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetOfficialOutputPrice(v)
	})
}

// AddOfficialOutputPrice adds v to the "official_output_price" field.
func (u *PricingModelUpsertBulk) AddOfficialOutputPrice(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddOfficialOutputPrice(v)
	})
}

// UpdateOfficialOutputPrice sets the "official_output_price" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateOfficialOutputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateOfficialOutputPrice()
	})
}

// ClearOfficialOutputPrice clears the value of the "official_output_price" field.
func (u *PricingModelUpsertBulk) ClearOfficialOutputPrice() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearOfficialOutputPrice()
	})
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (u *PricingModelUpsertBulk) SetImagePricingJSON(v string) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetImagePricingJSON(v)
	})
}

// UpdateImagePricingJSON sets the "image_pricing_json" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateImagePricingJSON() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateImagePricingJSON()
	})
}

// ClearImagePricingJSON clears the value of the "image_pricing_json" field.
func (u *PricingModelUpsertBulk) ClearImagePricingJSON() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.ClearImagePricingJSON()
	})
}

// SetSavingPercent sets the "saving_percent" field.
func (u *PricingModelUpsertBulk) SetSavingPercent(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.SetSavingPercent(v)
	})
}

// AddSavingPercent adds v to the "saving_percent" field.
func (u *PricingModelUpsertBulk) AddSavingPercent(v float64) *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.AddSavingPercent(v)
	})
}

// UpdateSavingPercent sets the "saving_percent" field to the value that was provided on create.
func (u *PricingModelUpsertBulk) UpdateSavingPercent() *PricingModelUpsertBulk {
	return u.Update(func(s *PricingModelUpsert) {
		s.UpdateSavingPercent()
	})
}

// Exec executes the query.
func (u *PricingModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PricingModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
