// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/pricingmodel"
)

// PricingModelUpdate is the builder for updating PricingModel entities.
type PricingModelUpdate struct {
	config
	hooks    []Hook
	mutation *PricingModelMutation
}

// Where appends a list predicates to the PricingModelUpdate builder.
func (_u *PricingModelUpdate) Where(ps ...predicate.PricingModel) *PricingModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingModelUpdate) SetUpdatedAt(v time.Time) *PricingModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *PricingModelUpdate) SetModel(v string) *PricingModelUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableModel(v *string) *PricingModelUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *PricingModelUpdate) SetModelType(v string) *PricingModelUpdate {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableModelType(v *string) *PricingModelUpdate {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetUserType sets the "user_type" field.
func (_u *PricingModelUpdate) SetUserType(v string) *PricingModelUpdate {
	_u.mutation.SetUserType(v)
	return _u
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableUserType(v *string) *PricingModelUpdate {
	if v != nil {
		_u.SetUserType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingModelUpdate) SetEnabled(v bool) *PricingModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableEnabled(v *bool) *PricingModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *PricingModelUpdate) SetInputPrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableInputPrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *PricingModelUpdate) AddInputPrice(v float64) *PricingModelUpdate {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *PricingModelUpdate) ClearInputPrice() *PricingModelUpdate {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *PricingModelUpdate) SetOutputPrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableOutputPrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *PricingModelUpdate) AddOutputPrice(v float64) *PricingModelUpdate {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *PricingModelUpdate) ClearOutputPrice() *PricingModelUpdate {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *PricingModelUpdate) SetCacheReadPrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableCacheReadPrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *PricingModelUpdate) AddCacheReadPrice(v float64) *PricingModelUpdate {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *PricingModelUpdate) ClearCacheReadPrice() *PricingModelUpdate {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *PricingModelUpdate) SetCacheWritePrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableCacheWritePrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *PricingModelUpdate) AddCacheWritePrice(v float64) *PricingModelUpdate {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *PricingModelUpdate) ClearCacheWritePrice() *PricingModelUpdate {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (_u *PricingModelUpdate) SetOfficialInputPrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetOfficialInputPrice()
	_u.mutation.SetOfficialInputPrice(v)
	return _u
}

// SetNillableOfficialInputPrice sets the "official_input_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableOfficialInputPrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetOfficialInputPrice(*v)
	}
	return _u
}

// AddOfficialInputPrice adds value to the "official_input_price" field.
func (_u *PricingModelUpdate) AddOfficialInputPrice(v float64) *PricingModelUpdate {
	_u.mutation.AddOfficialInputPrice(v)
	return _u
}

// ClearOfficialInputPrice clears the value of the "official_input_price" field.
func (_u *PricingModelUpdate) ClearOfficialInputPrice() *PricingModelUpdate {
	_u.mutation.ClearOfficialInputPrice()
	return _u
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (_u *PricingModelUpdate) SetOfficialOutputPrice(v float64) *PricingModelUpdate {
	_u.mutation.ResetOfficialOutputPrice()
	_u.mutation.SetOfficialOutputPrice(v)
	return _u
}

// SetNillableOfficialOutputPrice sets the "official_output_price" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableOfficialOutputPrice(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetOfficialOutputPrice(*v)
	}
	return _u
}

// AddOfficialOutputPrice adds value to the "official_output_price" field.
func (_u *PricingModelUpdate) AddOfficialOutputPrice(v float64) *PricingModelUpdate {
	_u.mutation.AddOfficialOutputPrice(v)
	return _u
}

// ClearOfficialOutputPrice clears the value of the "official_output_price" field.
func (_u *PricingModelUpdate) ClearOfficialOutputPrice() *PricingModelUpdate {
	_u.mutation.ClearOfficialOutputPrice()
	return _u
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (_u *PricingModelUpdate) SetImagePricingJSON(v string) *PricingModelUpdate {
	_u.mutation.SetImagePricingJSON(v)
	return _u
}

// SetNillableImagePricingJSON sets the "image_pricing_json" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableImagePricingJSON(v *string) *PricingModelUpdate {
	if v != nil {
		_u.SetImagePricingJSON(*v)
	}
	return _u
}

// ClearImagePricingJSON clears the value of the "image_pricing_json" field.
func (_u *PricingModelUpdate) ClearImagePricingJSON() *PricingModelUpdate {
	_u.mutation.ClearImagePricingJSON()
	return _u
}

// SetSavingPercent sets the "saving_percent" field.
func (_u *PricingModelUpdate) SetSavingPercent(v float64) *PricingModelUpdate {
	_u.mutation.ResetSavingPercent()
	_u.mutation.SetSavingPercent(v)
	return _u
}

// SetNillableSavingPercent sets the "saving_percent" field if the given value is not nil.
func (_u *PricingModelUpdate) SetNillableSavingPercent(v *float64) *PricingModelUpdate {
	if v != nil {
		_u.SetSavingPercent(*v)
	}
	return _u
}

// AddSavingPercent adds value to the "saving_percent" field.
func (_u *PricingModelUpdate) AddSavingPercent(v float64) *PricingModelUpdate {
	_u.mutation.AddSavingPercent(v)
	return _u
}

// Mutation returns the PricingModelMutation object of the builder.
func (_u *PricingModelUpdate) Mutation() *PricingModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pricingmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingModelUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := pricingmodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelType(); ok {
		if err := pricingmodel.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserType(); ok {
		if err := pricingmodel.UserTypeValidator(v); err != nil {
			return &ValidationError{Name: "user_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.user_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingmodel.Table, pricingmodel.Columns, sqlgraph.NewFieldSpec(pricingmodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(pricingmodel.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(pricingmodel.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserType(); ok {
		_spec.SetField(pricingmodel.FieldUserType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(pricingmodel.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(pricingmodel.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfficialInputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfficialInputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfficialInputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfficialOutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfficialOutputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfficialOutputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePricingJSON(); ok {
		_spec.SetField(pricingmodel.FieldImagePricingJSON, field.TypeString, value)
	}
	if _u.mutation.ImagePricingJSONCleared() {
		_spec.ClearField(pricingmodel.FieldImagePricingJSON, field.TypeString)
	}
	if value, ok := _u.mutation.SavingPercent(); ok {
		_spec.SetField(pricingmodel.FieldSavingPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSavingPercent(); ok {
		_spec.AddField(pricingmodel.FieldSavingPercent, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingModelUpdateOne is the builder for updating a single PricingModel entity.
type PricingModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingModelUpdateOne) SetUpdatedAt(v time.Time) *PricingModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *PricingModelUpdateOne) SetModel(v string) *PricingModelUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableModel(v *string) *PricingModelUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *PricingModelUpdateOne) SetModelType(v string) *PricingModelUpdateOne {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableModelType(v *string) *PricingModelUpdateOne {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetUserType sets the "user_type" field.
func (_u *PricingModelUpdateOne) SetUserType(v string) *PricingModelUpdateOne {
	_u.mutation.SetUserType(v)
	return _u
}

// SetNillableUserType sets the "user_type" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableUserType(v *string) *PricingModelUpdateOne {
	if v != nil {
		_u.SetUserType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingModelUpdateOne) SetEnabled(v bool) *PricingModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableEnabled(v *bool) *PricingModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetInputPrice sets the "input_price" field.
func (_u *PricingModelUpdateOne) SetInputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetInputPrice()
	_u.mutation.SetInputPrice(v)
	return _u
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableInputPrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetInputPrice(*v)
	}
	return _u
}

// AddInputPrice adds value to the "input_price" field.
func (_u *PricingModelUpdateOne) AddInputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddInputPrice(v)
	return _u
}

// ClearInputPrice clears the value of the "input_price" field.
func (_u *PricingModelUpdateOne) ClearInputPrice() *PricingModelUpdateOne {
	_u.mutation.ClearInputPrice()
	return _u
}

// SetOutputPrice sets the "output_price" field.
func (_u *PricingModelUpdateOne) SetOutputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetOutputPrice()
	_u.mutation.SetOutputPrice(v)
	return _u
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableOutputPrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetOutputPrice(*v)
	}
	return _u
}

// AddOutputPrice adds value to the "output_price" field.
func (_u *PricingModelUpdateOne) AddOutputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddOutputPrice(v)
	return _u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (_u *PricingModelUpdateOne) ClearOutputPrice() *PricingModelUpdateOne {
	_u.mutation.ClearOutputPrice()
	return _u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_u *PricingModelUpdateOne) SetCacheReadPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetCacheReadPrice()
	_u.mutation.SetCacheReadPrice(v)
	return _u
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableCacheReadPrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetCacheReadPrice(*v)
	}
	return _u
}

// AddCacheReadPrice adds value to the "cache_read_price" field.
func (_u *PricingModelUpdateOne) AddCacheReadPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddCacheReadPrice(v)
	return _u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (_u *PricingModelUpdateOne) ClearCacheReadPrice() *PricingModelUpdateOne {
	_u.mutation.ClearCacheReadPrice()
	return _u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_u *PricingModelUpdateOne) SetCacheWritePrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetCacheWritePrice()
	_u.mutation.SetCacheWritePrice(v)
	return _u
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableCacheWritePrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetCacheWritePrice(*v)
	}
	return _u
}

// AddCacheWritePrice adds value to the "cache_write_price" field.
func (_u *PricingModelUpdateOne) AddCacheWritePrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddCacheWritePrice(v)
	return _u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (_u *PricingModelUpdateOne) ClearCacheWritePrice() *PricingModelUpdateOne {
	_u.mutation.ClearCacheWritePrice()
	return _u
}

// SetOfficialInputPrice sets the "official_input_price" field.
func (_u *PricingModelUpdateOne) SetOfficialInputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetOfficialInputPrice()
	_u.mutation.SetOfficialInputPrice(v)
	return _u
}

// SetNillableOfficialInputPrice sets the "official_input_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableOfficialInputPrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetOfficialInputPrice(*v)
	}
	return _u
}

// AddOfficialInputPrice adds value to the "official_input_price" field.
func (_u *PricingModelUpdateOne) AddOfficialInputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddOfficialInputPrice(v)
	return _u
}

// ClearOfficialInputPrice clears the value of the "official_input_price" field.
func (_u *PricingModelUpdateOne) ClearOfficialInputPrice() *PricingModelUpdateOne {
	_u.mutation.ClearOfficialInputPrice()
	return _u
}

// SetOfficialOutputPrice sets the "official_output_price" field.
func (_u *PricingModelUpdateOne) SetOfficialOutputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetOfficialOutputPrice()
	_u.mutation.SetOfficialOutputPrice(v)
	return _u
}

// SetNillableOfficialOutputPrice sets the "official_output_price" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableOfficialOutputPrice(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetOfficialOutputPrice(*v)
	}
	return _u
}

// AddOfficialOutputPrice adds value to the "official_output_price" field.
func (_u *PricingModelUpdateOne) AddOfficialOutputPrice(v float64) *PricingModelUpdateOne {
	_u.mutation.AddOfficialOutputPrice(v)
	return _u
}

// ClearOfficialOutputPrice clears the value of the "official_output_price" field.
func (_u *PricingModelUpdateOne) ClearOfficialOutputPrice() *PricingModelUpdateOne {
	_u.mutation.ClearOfficialOutputPrice()
	return _u
}

// SetImagePricingJSON sets the "image_pricing_json" field.
func (_u *PricingModelUpdateOne) SetImagePricingJSON(v string) *PricingModelUpdateOne {
	_u.mutation.SetImagePricingJSON(v)
	return _u
}

// SetNillableImagePricingJSON sets the "image_pricing_json" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableImagePricingJSON(v *string) *PricingModelUpdateOne {
	if v != nil {
		_u.SetImagePricingJSON(*v)
	}
	return _u
}

// ClearImagePricingJSON clears the value of the "image_pricing_json" field.
func (_u *PricingModelUpdateOne) ClearImagePricingJSON() *PricingModelUpdateOne {
	_u.mutation.ClearImagePricingJSON()
	return _u
}

// SetSavingPercent sets the "saving_percent" field.
func (_u *PricingModelUpdateOne) SetSavingPercent(v float64) *PricingModelUpdateOne {
	_u.mutation.ResetSavingPercent()
	_u.mutation.SetSavingPercent(v)
	return _u
}

// SetNillableSavingPercent sets the "saving_percent" field if the given value is not nil.
func (_u *PricingModelUpdateOne) SetNillableSavingPercent(v *float64) *PricingModelUpdateOne {
	if v != nil {
		_u.SetSavingPercent(*v)
	}
	return _u
}

// AddSavingPercent adds value to the "saving_percent" field.
func (_u *PricingModelUpdateOne) AddSavingPercent(v float64) *PricingModelUpdateOne {
	_u.mutation.AddSavingPercent(v)
	return _u
}

// Mutation returns the PricingModelMutation object of the builder.
func (_u *PricingModelUpdateOne) Mutation() *PricingModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the PricingModelUpdate builder.
func (_u *PricingModelUpdateOne) Where(ps ...predicate.PricingModel) *PricingModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingModelUpdateOne) Select(field string, fields ...string) *PricingModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingModel entity.
func (_u *PricingModelUpdateOne) Save(ctx context.Context) (*PricingModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingModelUpdateOne) SaveX(ctx context.Context) *PricingModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pricingmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingModelUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := pricingmodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelType(); ok {
		if err := pricingmodel.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserType(); ok {
		if err := pricingmodel.UserTypeValidator(v); err != nil {
			return &ValidationError{Name: "user_type", err: fmt.Errorf(`ent: validator failed for field "PricingModel.user_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingModelUpdateOne) sqlSave(ctx context.Context) (_node *PricingModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingmodel.Table, pricingmodel.Columns, sqlgraph.NewFieldSpec(pricingmodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingmodel.FieldID)
		for _, f := range fields {
			if !pricingmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(pricingmodel.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(pricingmodel.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserType(); ok {
		_spec.SetField(pricingmodel.FieldUserType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InputPrice(); ok {
		_spec.SetField(pricingmodel.FieldInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPrice(); ok {
		_spec.AddField(pricingmodel.FieldInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.InputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OutputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheReadPrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPrice(); ok {
		_spec.AddField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheReadPriceCleared() {
		_spec.ClearField(pricingmodel.FieldCacheReadPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CacheWritePrice(); ok {
		_spec.SetField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePrice(); ok {
		_spec.AddField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64, value)
	}
	if _u.mutation.CacheWritePriceCleared() {
		_spec.ClearField(pricingmodel.FieldCacheWritePrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfficialInputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfficialInputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfficialInputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOfficialInputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.OfficialOutputPrice(); ok {
		_spec.SetField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOfficialOutputPrice(); ok {
		_spec.AddField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OfficialOutputPriceCleared() {
		_spec.ClearField(pricingmodel.FieldOfficialOutputPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ImagePricingJSON(); ok {
		_spec.SetField(pricingmodel.FieldImagePricingJSON, field.TypeString, value)
	}
	if _u.mutation.ImagePricingJSONCleared() {
		_spec.ClearField(pricingmodel.FieldImagePricingJSON, field.TypeString)
	}
	if value, ok := _u.mutation.SavingPercent(); ok {
		_spec.SetField(pricingmodel.FieldSavingPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSavingPercent(); ok {
		_spec.AddField(pricingmodel.FieldSavingPercent, field.TypeFloat64, value)
	}
	_node = &PricingModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
