// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providerconnectsession"
)

// ProviderConnectSessionUpdate is the builder for updating ProviderConnectSession entities.
type ProviderConnectSessionUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderConnectSessionMutation
}

// Where appends a list predicates to the ProviderConnectSessionUpdate builder.
func (_u *ProviderConnectSessionUpdate) Where(ps ...predicate.ProviderConnectSession) *ProviderConnectSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderConnectSessionUpdate) SetUpdatedAt(v time.Time) *ProviderConnectSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (_u *ProviderConnectSessionUpdate) SetExternalProviderAccountID(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetExternalProviderAccountID(v)
	return _u
}

// SetNillableExternalProviderAccountID sets the "external_provider_account_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableExternalProviderAccountID(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetExternalProviderAccountID(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *ProviderConnectSessionUpdate) SetProviderType(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableProviderType(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProviderConnectSessionUpdate) SetRegion(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableRegion(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProviderConnectSessionUpdate) ClearRegion() *ProviderConnectSessionUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProviderConnectSessionUpdate) SetProxyID(v int64) *ProviderConnectSessionUpdate {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableProxyID(v *int64) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *ProviderConnectSessionUpdate) AddProxyID(v int64) *ProviderConnectSessionUpdate {
	_u.mutation.AddProxyID(v)
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ProviderConnectSessionUpdate) ClearProxyID() *ProviderConnectSessionUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderConnectSessionUpdate) SetStatus(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableStatus(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOauthSessionID sets the "oauth_session_id" field.
func (_u *ProviderConnectSessionUpdate) SetOauthSessionID(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetOauthSessionID(v)
	return _u
}

// SetNillableOauthSessionID sets the "oauth_session_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableOauthSessionID(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetOauthSessionID(*v)
	}
	return _u
}

// ClearOauthSessionID clears the value of the "oauth_session_id" field.
func (_u *ProviderConnectSessionUpdate) ClearOauthSessionID() *ProviderConnectSessionUpdate {
	_u.mutation.ClearOauthSessionID()
	return _u
}

// SetSub2apiAccountID sets the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdate) SetSub2apiAccountID(v int64) *ProviderConnectSessionUpdate {
	_u.mutation.ResetSub2apiAccountID()
	_u.mutation.SetSub2apiAccountID(v)
	return _u
}

// SetNillableSub2apiAccountID sets the "sub2api_account_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableSub2apiAccountID(v *int64) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetSub2apiAccountID(*v)
	}
	return _u
}

// AddSub2apiAccountID adds value to the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdate) AddSub2apiAccountID(v int64) *ProviderConnectSessionUpdate {
	_u.mutation.AddSub2apiAccountID(v)
	return _u
}

// ClearSub2apiAccountID clears the value of the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdate) ClearSub2apiAccountID() *ProviderConnectSessionUpdate {
	_u.mutation.ClearSub2apiAccountID()
	return _u
}

// SetCallbackURL sets the "callback_url" field.
func (_u *ProviderConnectSessionUpdate) SetCallbackURL(v string) *ProviderConnectSessionUpdate {
	_u.mutation.SetCallbackURL(v)
	return _u
}

// SetNillableCallbackURL sets the "callback_url" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableCallbackURL(v *string) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetCallbackURL(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProviderConnectSessionUpdate) SetExpiresAt(v time.Time) *ProviderConnectSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableExpiresAt(v *time.Time) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ProviderConnectSessionUpdate) SetCompletedAt(v time.Time) *ProviderConnectSessionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdate) SetNillableCompletedAt(v *time.Time) *ProviderConnectSessionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ProviderConnectSessionUpdate) ClearCompletedAt() *ProviderConnectSessionUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ProviderConnectSessionMutation object of the builder.
func (_u *ProviderConnectSessionUpdate) Mutation() *ProviderConnectSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderConnectSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderConnectSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderConnectSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderConnectSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderConnectSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerconnectsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderConnectSessionUpdate) check() error {
	if v, ok := _u.mutation.ExternalProviderAccountID(); ok {
		if err := providerconnectsession.ExternalProviderAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_provider_account_id", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.external_provider_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := providerconnectsession.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := providerconnectsession.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providerconnectsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSessionID(); ok {
		if err := providerconnectsession.OauthSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_session_id", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.oauth_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallbackURL(); ok {
		if err := providerconnectsession.CallbackURLValidator(v); err != nil {
			return &ValidationError{Name: "callback_url", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.callback_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderConnectSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerconnectsession.Table, providerconnectsession.Columns, sqlgraph.NewFieldSpec(providerconnectsession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerconnectsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalProviderAccountID(); ok {
		_spec.SetField(providerconnectsession.FieldExternalProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(providerconnectsession.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(providerconnectsession.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(providerconnectsession.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(providerconnectsession.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(providerconnectsession.FieldProxyID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(providerconnectsession.FieldProxyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providerconnectsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthSessionID(); ok {
		_spec.SetField(providerconnectsession.FieldOauthSessionID, field.TypeString, value)
	}
	if _u.mutation.OauthSessionIDCleared() {
		_spec.ClearField(providerconnectsession.FieldOauthSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Sub2apiAccountID(); ok {
		_spec.SetField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSub2apiAccountID(); ok {
		_spec.AddField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64, value)
	}
	if _u.mutation.Sub2apiAccountIDCleared() {
		_spec.ClearField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CallbackURL(); ok {
		_spec.SetField(providerconnectsession.FieldCallbackURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(providerconnectsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(providerconnectsession.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(providerconnectsession.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerconnectsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderConnectSessionUpdateOne is the builder for updating a single ProviderConnectSession entity.
type ProviderConnectSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderConnectSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderConnectSessionUpdateOne) SetUpdatedAt(v time.Time) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (_u *ProviderConnectSessionUpdateOne) SetExternalProviderAccountID(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetExternalProviderAccountID(v)
	return _u
}

// SetNillableExternalProviderAccountID sets the "external_provider_account_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableExternalProviderAccountID(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetExternalProviderAccountID(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *ProviderConnectSessionUpdateOne) SetProviderType(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableProviderType(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProviderConnectSessionUpdateOne) SetRegion(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableRegion(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProviderConnectSessionUpdateOne) ClearRegion() *ProviderConnectSessionUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProviderConnectSessionUpdateOne) SetProxyID(v int64) *ProviderConnectSessionUpdateOne {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableProxyID(v *int64) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *ProviderConnectSessionUpdateOne) AddProxyID(v int64) *ProviderConnectSessionUpdateOne {
	_u.mutation.AddProxyID(v)
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ProviderConnectSessionUpdateOne) ClearProxyID() *ProviderConnectSessionUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderConnectSessionUpdateOne) SetStatus(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableStatus(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOauthSessionID sets the "oauth_session_id" field.
func (_u *ProviderConnectSessionUpdateOne) SetOauthSessionID(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetOauthSessionID(v)
	return _u
}

// SetNillableOauthSessionID sets the "oauth_session_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableOauthSessionID(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetOauthSessionID(*v)
	}
	return _u
}

// ClearOauthSessionID clears the value of the "oauth_session_id" field.
func (_u *ProviderConnectSessionUpdateOne) ClearOauthSessionID() *ProviderConnectSessionUpdateOne {
	_u.mutation.ClearOauthSessionID()
	return _u
}

// SetSub2apiAccountID sets the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdateOne) SetSub2apiAccountID(v int64) *ProviderConnectSessionUpdateOne {
	_u.mutation.ResetSub2apiAccountID()
	_u.mutation.SetSub2apiAccountID(v)
	return _u
}

// SetNillableSub2apiAccountID sets the "sub2api_account_id" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableSub2apiAccountID(v *int64) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetSub2apiAccountID(*v)
	}
	return _u
}

// AddSub2apiAccountID adds value to the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdateOne) AddSub2apiAccountID(v int64) *ProviderConnectSessionUpdateOne {
	_u.mutation.AddSub2apiAccountID(v)
	return _u
}

// ClearSub2apiAccountID clears the value of the "sub2api_account_id" field.
func (_u *ProviderConnectSessionUpdateOne) ClearSub2apiAccountID() *ProviderConnectSessionUpdateOne {
	_u.mutation.ClearSub2apiAccountID()
	return _u
}

// SetCallbackURL sets the "callback_url" field.
func (_u *ProviderConnectSessionUpdateOne) SetCallbackURL(v string) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetCallbackURL(v)
	return _u
}

// SetNillableCallbackURL sets the "callback_url" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableCallbackURL(v *string) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetCallbackURL(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProviderConnectSessionUpdateOne) SetExpiresAt(v time.Time) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ProviderConnectSessionUpdateOne) SetCompletedAt(v time.Time) *ProviderConnectSessionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ProviderConnectSessionUpdateOne) SetNillableCompletedAt(v *time.Time) *ProviderConnectSessionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ProviderConnectSessionUpdateOne) ClearCompletedAt() *ProviderConnectSessionUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the ProviderConnectSessionMutation object of the builder.
func (_u *ProviderConnectSessionUpdateOne) Mutation() *ProviderConnectSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderConnectSessionUpdate builder.
func (_u *ProviderConnectSessionUpdateOne) Where(ps ...predicate.ProviderConnectSession) *ProviderConnectSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderConnectSessionUpdateOne) Select(field string, fields ...string) *ProviderConnectSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderConnectSession entity.
func (_u *ProviderConnectSessionUpdateOne) Save(ctx context.Context) (*ProviderConnectSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderConnectSessionUpdateOne) SaveX(ctx context.Context) *ProviderConnectSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderConnectSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderConnectSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderConnectSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := providerconnectsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderConnectSessionUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalProviderAccountID(); ok {
		if err := providerconnectsession.ExternalProviderAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_provider_account_id", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.external_provider_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := providerconnectsession.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := providerconnectsession.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := providerconnectsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSessionID(); ok {
		if err := providerconnectsession.OauthSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_session_id", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.oauth_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CallbackURL(); ok {
		if err := providerconnectsession.CallbackURLValidator(v); err != nil {
			return &ValidationError{Name: "callback_url", err: fmt.Errorf(`ent: validator failed for field "ProviderConnectSession.callback_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderConnectSessionUpdateOne) sqlSave(ctx context.Context) (_node *ProviderConnectSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providerconnectsession.Table, providerconnectsession.Columns, sqlgraph.NewFieldSpec(providerconnectsession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderConnectSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providerconnectsession.FieldID)
		for _, f := range fields {
			if !providerconnectsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providerconnectsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(providerconnectsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalProviderAccountID(); ok {
		_spec.SetField(providerconnectsession.FieldExternalProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(providerconnectsession.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(providerconnectsession.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(providerconnectsession.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(providerconnectsession.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(providerconnectsession.FieldProxyID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(providerconnectsession.FieldProxyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providerconnectsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthSessionID(); ok {
		_spec.SetField(providerconnectsession.FieldOauthSessionID, field.TypeString, value)
	}
	if _u.mutation.OauthSessionIDCleared() {
		_spec.ClearField(providerconnectsession.FieldOauthSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Sub2apiAccountID(); ok {
		_spec.SetField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSub2apiAccountID(); ok {
		_spec.AddField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64, value)
	}
	if _u.mutation.Sub2apiAccountIDCleared() {
		_spec.ClearField(providerconnectsession.FieldSub2apiAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CallbackURL(); ok {
		_spec.SetField(providerconnectsession.FieldCallbackURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(providerconnectsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(providerconnectsession.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(providerconnectsession.FieldCompletedAt, field.TypeTime)
	}
	_node = &ProviderConnectSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providerconnectsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
