// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providerconnectsession"
)

// ProviderConnectSession is the model entity for the ProviderConnectSession schema.
type ProviderConnectSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Portal 侧账号引用（pa_<uuid>）。同一引用可多次开启会话（重试），非唯一。
	ExternalProviderAccountID string `json:"external_provider_account_id,omitempty"`
	// 目标 AI 平台类型（claude/codex/openai/gemini …）。
	ProviderType string `json:"provider_type,omitempty"`
	// 请求的出口区域偏好；NULL = 未指定，由分配策略决定。
	Region *string `json:"region,omitempty"`
	// 分配到的代理 id；pending 早期可为 NULL，分配后写入。
	ProxyID *int64 `json:"proxy_id,omitempty"`
	// pending | authorized | completed | expired | failed
	Status string `json:"status,omitempty"`
	// 关联的 OAuth 内存会话 id；ExchangeCode 的必需入参。
	OauthSessionID *string `json:"oauth_session_id,omitempty"`
	// 完成后创建的 Sub2API 账号 id；completed 时写入，幂等重入据此返回已有结果。
	Sub2apiAccountID *int64 `json:"sub2api_account_id,omitempty"`
	// Portal 事件回调地址（webhook 目标）。
	CallbackURL string `json:"callback_url,omitempty"`
	// 会话过期时间；过期未完成的会话由后续阶段的清扫置为 expired。
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// 到达 completed 终态的时间。
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderConnectSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providerconnectsession.FieldID, providerconnectsession.FieldProxyID, providerconnectsession.FieldSub2apiAccountID:
			values[i] = new(sql.NullInt64)
		case providerconnectsession.FieldExternalProviderAccountID, providerconnectsession.FieldProviderType, providerconnectsession.FieldRegion, providerconnectsession.FieldStatus, providerconnectsession.FieldOauthSessionID, providerconnectsession.FieldCallbackURL:
			values[i] = new(sql.NullString)
		case providerconnectsession.FieldCreatedAt, providerconnectsession.FieldUpdatedAt, providerconnectsession.FieldExpiresAt, providerconnectsession.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderConnectSession fields.
func (_m *ProviderConnectSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providerconnectsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providerconnectsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case providerconnectsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case providerconnectsession.FieldExternalProviderAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_provider_account_id", values[i])
			} else if value.Valid {
				_m.ExternalProviderAccountID = value.String
			}
		case providerconnectsession.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case providerconnectsession.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = new(string)
				*_m.Region = value.String
			}
		case providerconnectsession.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = new(int64)
				*_m.ProxyID = value.Int64
			}
		case providerconnectsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case providerconnectsession.FieldOauthSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_session_id", values[i])
			} else if value.Valid {
				_m.OauthSessionID = new(string)
				*_m.OauthSessionID = value.String
			}
		case providerconnectsession.FieldSub2apiAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub2api_account_id", values[i])
			} else if value.Valid {
				_m.Sub2apiAccountID = new(int64)
				*_m.Sub2apiAccountID = value.Int64
			}
		case providerconnectsession.FieldCallbackURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_url", values[i])
			} else if value.Valid {
				_m.CallbackURL = value.String
			}
		case providerconnectsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case providerconnectsession.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderConnectSession.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderConnectSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderConnectSession.
// Note that you need to call ProviderConnectSession.Unwrap() before calling this method if this ProviderConnectSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderConnectSession) Update() *ProviderConnectSessionUpdateOne {
	return NewProviderConnectSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderConnectSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderConnectSession) Unwrap() *ProviderConnectSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderConnectSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderConnectSession) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderConnectSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("external_provider_account_id=")
	builder.WriteString(_m.ExternalProviderAccountID)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	if v := _m.Region; v != nil {
		builder.WriteString("region=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProxyID; v != nil {
		builder.WriteString("proxy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.OauthSessionID; v != nil {
		builder.WriteString("oauth_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Sub2apiAccountID; v != nil {
		builder.WriteString("sub2api_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("callback_url=")
	builder.WriteString(_m.CallbackURL)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProviderConnectSessions is a parsable slice of ProviderConnectSession.
type ProviderConnectSessions []*ProviderConnectSession
