// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/proxyallocation"
)

// ProxyAllocationCreate is the builder for creating a ProxyAllocation entity.
type ProxyAllocationCreate struct {
	config
	mutation *ProxyAllocationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyAllocationCreate) SetCreatedAt(v time.Time) *ProxyAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableCreatedAt(v *time.Time) *ProxyAllocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyAllocationCreate) SetUpdatedAt(v time.Time) *ProxyAllocationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableUpdatedAt(v *time.Time) *ProxyAllocationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *ProxyAllocationCreate) SetProxyID(v int64) *ProxyAllocationCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (_c *ProxyAllocationCreate) SetExternalProviderAccountID(v string) *ProxyAllocationCreate {
	_c.mutation.SetExternalProviderAccountID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ProxyAllocationCreate) SetAccountID(v int64) *ProxyAllocationCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableAccountID(v *int64) *ProxyAllocationCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *ProxyAllocationCreate) SetRegion(v string) *ProxyAllocationCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableRegion(v *string) *ProxyAllocationCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetAllocationStatus sets the "allocation_status" field.
func (_c *ProxyAllocationCreate) SetAllocationStatus(v string) *ProxyAllocationCreate {
	_c.mutation.SetAllocationStatus(v)
	return _c
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableAllocationStatus(v *string) *ProxyAllocationCreate {
	if v != nil {
		_c.SetAllocationStatus(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *ProxyAllocationCreate) SetAssignedAt(v time.Time) *ProxyAllocationCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableAssignedAt(v *time.Time) *ProxyAllocationCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *ProxyAllocationCreate) SetReleasedAt(v time.Time) *ProxyAllocationCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableReleasedAt(v *time.Time) *ProxyAllocationCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetReleaseReason sets the "release_reason" field.
func (_c *ProxyAllocationCreate) SetReleaseReason(v string) *ProxyAllocationCreate {
	_c.mutation.SetReleaseReason(v)
	return _c
}

// SetNillableReleaseReason sets the "release_reason" field if the given value is not nil.
func (_c *ProxyAllocationCreate) SetNillableReleaseReason(v *string) *ProxyAllocationCreate {
	if v != nil {
		_c.SetReleaseReason(*v)
	}
	return _c
}

// Mutation returns the ProxyAllocationMutation object of the builder.
func (_c *ProxyAllocationCreate) Mutation() *ProxyAllocationMutation {
	return _c.mutation
}

// Save creates the ProxyAllocation in the database.
func (_c *ProxyAllocationCreate) Save(ctx context.Context) (*ProxyAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyAllocationCreate) SaveX(ctx context.Context) *ProxyAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyAllocationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyallocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyallocation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AllocationStatus(); !ok {
		v := proxyallocation.DefaultAllocationStatus
		_c.mutation.SetAllocationStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyAllocationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyAllocation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyAllocation.updated_at"`)}
	}
	if _, ok := _c.mutation.ProxyID(); !ok {
		return &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing required field "ProxyAllocation.proxy_id"`)}
	}
	if _, ok := _c.mutation.ExternalProviderAccountID(); !ok {
		return &ValidationError{Name: "external_provider_account_id", err: errors.New(`ent: missing required field "ProxyAllocation.external_provider_account_id"`)}
	}
	if v, ok := _c.mutation.ExternalProviderAccountID(); ok {
		if err := proxyallocation.ExternalProviderAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_provider_account_id", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.external_provider_account_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Region(); ok {
		if err := proxyallocation.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.region": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllocationStatus(); !ok {
		return &ValidationError{Name: "allocation_status", err: errors.New(`ent: missing required field "ProxyAllocation.allocation_status"`)}
	}
	if v, ok := _c.mutation.AllocationStatus(); ok {
		if err := proxyallocation.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.allocation_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReleaseReason(); ok {
		if err := proxyallocation.ReleaseReasonValidator(v); err != nil {
			return &ValidationError{Name: "release_reason", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.release_reason": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxyAllocationCreate) sqlSave(ctx context.Context) (*ProxyAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyAllocationCreate) createSpec() (*ProxyAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyallocation.Table, sqlgraph.NewFieldSpec(proxyallocation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProxyID(); ok {
		_spec.SetField(proxyallocation.FieldProxyID, field.TypeInt64, value)
		_node.ProxyID = value
	}
	if value, ok := _c.mutation.ExternalProviderAccountID(); ok {
		_spec.SetField(proxyallocation.FieldExternalProviderAccountID, field.TypeString, value)
		_node.ExternalProviderAccountID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(proxyallocation.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(proxyallocation.FieldRegion, field.TypeString, value)
		_node.Region = &value
	}
	if value, ok := _c.mutation.AllocationStatus(); ok {
		_spec.SetField(proxyallocation.FieldAllocationStatus, field.TypeString, value)
		_node.AllocationStatus = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(proxyallocation.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = &value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(proxyallocation.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = &value
	}
	if value, ok := _c.mutation.ReleaseReason(); ok {
		_spec.SetField(proxyallocation.FieldReleaseReason, field.TypeString, value)
		_node.ReleaseReason = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyAllocation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyAllocationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyAllocationCreate) OnConflict(opts ...sql.ConflictOption) *ProxyAllocationUpsertOne {
	_c.conflict = opts
	return &ProxyAllocationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyAllocationCreate) OnConflictColumns(columns ...string) *ProxyAllocationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyAllocationUpsertOne{
		create: _c,
	}
}

type (
	// ProxyAllocationUpsertOne is the builder for "upsert"-ing
	//  one ProxyAllocation node.
	ProxyAllocationUpsertOne struct {
		create *ProxyAllocationCreate
	}

	// ProxyAllocationUpsert is the "OnConflict" setter.
	ProxyAllocationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyAllocationUpsert) SetUpdatedAt(v time.Time) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateUpdatedAt() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldUpdatedAt)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *ProxyAllocationUpsert) SetProxyID(v int64) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateProxyID() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldProxyID)
	return u
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyAllocationUpsert) AddProxyID(v int64) *ProxyAllocationUpsert {
	u.Add(proxyallocation.FieldProxyID, v)
	return u
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (u *ProxyAllocationUpsert) SetExternalProviderAccountID(v string) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldExternalProviderAccountID, v)
	return u
}

// UpdateExternalProviderAccountID sets the "external_provider_account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateExternalProviderAccountID() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldExternalProviderAccountID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ProxyAllocationUpsert) SetAccountID(v int64) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateAccountID() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ProxyAllocationUpsert) AddAccountID(v int64) *ProxyAllocationUpsert {
	u.Add(proxyallocation.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ProxyAllocationUpsert) ClearAccountID() *ProxyAllocationUpsert {
	u.SetNull(proxyallocation.FieldAccountID)
	return u
}

// SetRegion sets the "region" field.
func (u *ProxyAllocationUpsert) SetRegion(v string) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldRegion, v)
	return u
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateRegion() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldRegion)
	return u
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyAllocationUpsert) ClearRegion() *ProxyAllocationUpsert {
	u.SetNull(proxyallocation.FieldRegion)
	return u
}

// SetAllocationStatus sets the "allocation_status" field.
func (u *ProxyAllocationUpsert) SetAllocationStatus(v string) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldAllocationStatus, v)
	return u
}

// UpdateAllocationStatus sets the "allocation_status" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateAllocationStatus() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldAllocationStatus)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *ProxyAllocationUpsert) SetAssignedAt(v time.Time) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateAssignedAt() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldAssignedAt)
	return u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *ProxyAllocationUpsert) ClearAssignedAt() *ProxyAllocationUpsert {
	u.SetNull(proxyallocation.FieldAssignedAt)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *ProxyAllocationUpsert) SetReleasedAt(v time.Time) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateReleasedAt() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldReleasedAt)
	return u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *ProxyAllocationUpsert) ClearReleasedAt() *ProxyAllocationUpsert {
	u.SetNull(proxyallocation.FieldReleasedAt)
	return u
}

// SetReleaseReason sets the "release_reason" field.
func (u *ProxyAllocationUpsert) SetReleaseReason(v string) *ProxyAllocationUpsert {
	u.Set(proxyallocation.FieldReleaseReason, v)
	return u
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *ProxyAllocationUpsert) UpdateReleaseReason() *ProxyAllocationUpsert {
	u.SetExcluded(proxyallocation.FieldReleaseReason)
	return u
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *ProxyAllocationUpsert) ClearReleaseReason() *ProxyAllocationUpsert {
	u.SetNull(proxyallocation.FieldReleaseReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyAllocationUpsertOne) UpdateNewValues() *ProxyAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxyallocation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyAllocationUpsertOne) Ignore() *ProxyAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyAllocationUpsertOne) DoNothing() *ProxyAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyAllocationCreate.OnConflict
// documentation for more info.
func (u *ProxyAllocationUpsertOne) Update(set func(*ProxyAllocationUpsert)) *ProxyAllocationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyAllocationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyAllocationUpsertOne) SetUpdatedAt(v time.Time) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateUpdatedAt() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ProxyAllocationUpsertOne) SetProxyID(v int64) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyAllocationUpsertOne) AddProxyID(v int64) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateProxyID() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateProxyID()
	})
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (u *ProxyAllocationUpsertOne) SetExternalProviderAccountID(v string) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetExternalProviderAccountID(v)
	})
}

// UpdateExternalProviderAccountID sets the "external_provider_account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateExternalProviderAccountID() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateExternalProviderAccountID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ProxyAllocationUpsertOne) SetAccountID(v int64) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ProxyAllocationUpsertOne) AddAccountID(v int64) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateAccountID() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ProxyAllocationUpsertOne) ClearAccountID() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearAccountID()
	})
}

// SetRegion sets the "region" field.
func (u *ProxyAllocationUpsertOne) SetRegion(v string) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateRegion() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateRegion()
	})
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyAllocationUpsertOne) ClearRegion() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearRegion()
	})
}

// SetAllocationStatus sets the "allocation_status" field.
func (u *ProxyAllocationUpsertOne) SetAllocationStatus(v string) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAllocationStatus(v)
	})
}

// UpdateAllocationStatus sets the "allocation_status" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateAllocationStatus() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAllocationStatus()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *ProxyAllocationUpsertOne) SetAssignedAt(v time.Time) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateAssignedAt() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *ProxyAllocationUpsertOne) ClearAssignedAt() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearAssignedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *ProxyAllocationUpsertOne) SetReleasedAt(v time.Time) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateReleasedAt() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *ProxyAllocationUpsertOne) ClearReleasedAt() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearReleasedAt()
	})
}

// SetReleaseReason sets the "release_reason" field.
func (u *ProxyAllocationUpsertOne) SetReleaseReason(v string) *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetReleaseReason(v)
	})
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *ProxyAllocationUpsertOne) UpdateReleaseReason() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateReleaseReason()
	})
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *ProxyAllocationUpsertOne) ClearReleaseReason() *ProxyAllocationUpsertOne {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearReleaseReason()
	})
}

// Exec executes the query.
func (u *ProxyAllocationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyAllocationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyAllocationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyAllocationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyAllocationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyAllocationCreateBulk is the builder for creating many ProxyAllocation entities in bulk.
type ProxyAllocationCreateBulk struct {
	config
	err      error
	builders []*ProxyAllocationCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyAllocation entities in the database.
func (_c *ProxyAllocationCreateBulk) Save(ctx context.Context) ([]*ProxyAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyAllocationCreateBulk) SaveX(ctx context.Context) []*ProxyAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyAllocation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyAllocationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyAllocationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyAllocationUpsertBulk {
	_c.conflict = opts
	return &ProxyAllocationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyAllocationCreateBulk) OnConflictColumns(columns ...string) *ProxyAllocationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyAllocationUpsertBulk{
		create: _c,
	}
}

// ProxyAllocationUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyAllocation nodes.
type ProxyAllocationUpsertBulk struct {
	create *ProxyAllocationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProxyAllocationUpsertBulk) UpdateNewValues() *ProxyAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxyallocation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyAllocation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyAllocationUpsertBulk) Ignore() *ProxyAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyAllocationUpsertBulk) DoNothing() *ProxyAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyAllocationCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyAllocationUpsertBulk) Update(set func(*ProxyAllocationUpsert)) *ProxyAllocationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyAllocationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyAllocationUpsertBulk) SetUpdatedAt(v time.Time) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateUpdatedAt() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *ProxyAllocationUpsertBulk) SetProxyID(v int64) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetProxyID(v)
	})
}

// AddProxyID adds v to the "proxy_id" field.
func (u *ProxyAllocationUpsertBulk) AddProxyID(v int64) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.AddProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateProxyID() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateProxyID()
	})
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (u *ProxyAllocationUpsertBulk) SetExternalProviderAccountID(v string) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetExternalProviderAccountID(v)
	})
}

// UpdateExternalProviderAccountID sets the "external_provider_account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateExternalProviderAccountID() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateExternalProviderAccountID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ProxyAllocationUpsertBulk) SetAccountID(v int64) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ProxyAllocationUpsertBulk) AddAccountID(v int64) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateAccountID() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *ProxyAllocationUpsertBulk) ClearAccountID() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearAccountID()
	})
}

// SetRegion sets the "region" field.
func (u *ProxyAllocationUpsertBulk) SetRegion(v string) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetRegion(v)
	})
}

// UpdateRegion sets the "region" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateRegion() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateRegion()
	})
}

// ClearRegion clears the value of the "region" field.
func (u *ProxyAllocationUpsertBulk) ClearRegion() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearRegion()
	})
}

// SetAllocationStatus sets the "allocation_status" field.
func (u *ProxyAllocationUpsertBulk) SetAllocationStatus(v string) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAllocationStatus(v)
	})
}

// UpdateAllocationStatus sets the "allocation_status" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateAllocationStatus() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAllocationStatus()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *ProxyAllocationUpsertBulk) SetAssignedAt(v time.Time) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateAssignedAt() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *ProxyAllocationUpsertBulk) ClearAssignedAt() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearAssignedAt()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *ProxyAllocationUpsertBulk) SetReleasedAt(v time.Time) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateReleasedAt() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateReleasedAt()
	})
}

// ClearReleasedAt clears the value of the "released_at" field.
func (u *ProxyAllocationUpsertBulk) ClearReleasedAt() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearReleasedAt()
	})
}

// SetReleaseReason sets the "release_reason" field.
func (u *ProxyAllocationUpsertBulk) SetReleaseReason(v string) *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.SetReleaseReason(v)
	})
}

// UpdateReleaseReason sets the "release_reason" field to the value that was provided on create.
func (u *ProxyAllocationUpsertBulk) UpdateReleaseReason() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.UpdateReleaseReason()
	})
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (u *ProxyAllocationUpsertBulk) ClearReleaseReason() *ProxyAllocationUpsertBulk {
	return u.Update(func(s *ProxyAllocationUpsert) {
		s.ClearReleaseReason()
	})
}

// Exec executes the query.
func (u *ProxyAllocationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyAllocationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyAllocationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyAllocationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
