// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxyallocation"
)

// ProxyAllocationUpdate is the builder for updating ProxyAllocation entities.
type ProxyAllocationUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyAllocationMutation
}

// Where appends a list predicates to the ProxyAllocationUpdate builder.
func (_u *ProxyAllocationUpdate) Where(ps ...predicate.ProxyAllocation) *ProxyAllocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyAllocationUpdate) SetUpdatedAt(v time.Time) *ProxyAllocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProxyAllocationUpdate) SetProxyID(v int64) *ProxyAllocationUpdate {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableProxyID(v *int64) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *ProxyAllocationUpdate) AddProxyID(v int64) *ProxyAllocationUpdate {
	_u.mutation.AddProxyID(v)
	return _u
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (_u *ProxyAllocationUpdate) SetExternalProviderAccountID(v string) *ProxyAllocationUpdate {
	_u.mutation.SetExternalProviderAccountID(v)
	return _u
}

// SetNillableExternalProviderAccountID sets the "external_provider_account_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableExternalProviderAccountID(v *string) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetExternalProviderAccountID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ProxyAllocationUpdate) SetAccountID(v int64) *ProxyAllocationUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableAccountID(v *int64) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ProxyAllocationUpdate) AddAccountID(v int64) *ProxyAllocationUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ProxyAllocationUpdate) ClearAccountID() *ProxyAllocationUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyAllocationUpdate) SetRegion(v string) *ProxyAllocationUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableRegion(v *string) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProxyAllocationUpdate) ClearRegion() *ProxyAllocationUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *ProxyAllocationUpdate) SetAllocationStatus(v string) *ProxyAllocationUpdate {
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableAllocationStatus(v *string) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *ProxyAllocationUpdate) SetAssignedAt(v time.Time) *ProxyAllocationUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableAssignedAt(v *time.Time) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *ProxyAllocationUpdate) ClearAssignedAt() *ProxyAllocationUpdate {
	_u.mutation.ClearAssignedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *ProxyAllocationUpdate) SetReleasedAt(v time.Time) *ProxyAllocationUpdate {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableReleasedAt(v *time.Time) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *ProxyAllocationUpdate) ClearReleasedAt() *ProxyAllocationUpdate {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetReleaseReason sets the "release_reason" field.
func (_u *ProxyAllocationUpdate) SetReleaseReason(v string) *ProxyAllocationUpdate {
	_u.mutation.SetReleaseReason(v)
	return _u
}

// SetNillableReleaseReason sets the "release_reason" field if the given value is not nil.
func (_u *ProxyAllocationUpdate) SetNillableReleaseReason(v *string) *ProxyAllocationUpdate {
	if v != nil {
		_u.SetReleaseReason(*v)
	}
	return _u
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (_u *ProxyAllocationUpdate) ClearReleaseReason() *ProxyAllocationUpdate {
	_u.mutation.ClearReleaseReason()
	return _u
}

// Mutation returns the ProxyAllocationMutation object of the builder.
func (_u *ProxyAllocationUpdate) Mutation() *ProxyAllocationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyAllocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyAllocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyAllocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyAllocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyAllocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyAllocationUpdate) check() error {
	if v, ok := _u.mutation.ExternalProviderAccountID(); ok {
		if err := proxyallocation.ExternalProviderAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_provider_account_id", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.external_provider_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxyallocation.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := proxyallocation.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseReason(); ok {
		if err := proxyallocation.ReleaseReasonValidator(v); err != nil {
			return &ValidationError{Name: "release_reason", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.release_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyAllocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyallocation.Table, proxyallocation.Columns, sqlgraph.NewFieldSpec(proxyallocation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(proxyallocation.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(proxyallocation.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExternalProviderAccountID(); ok {
		_spec.SetField(proxyallocation.FieldExternalProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(proxyallocation.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(proxyallocation.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(proxyallocation.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxyallocation.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(proxyallocation.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(proxyallocation.FieldAllocationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(proxyallocation.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(proxyallocation.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(proxyallocation.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(proxyallocation.FieldReleasedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleaseReason(); ok {
		_spec.SetField(proxyallocation.FieldReleaseReason, field.TypeString, value)
	}
	if _u.mutation.ReleaseReasonCleared() {
		_spec.ClearField(proxyallocation.FieldReleaseReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyAllocationUpdateOne is the builder for updating a single ProxyAllocation entity.
type ProxyAllocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyAllocationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyAllocationUpdateOne) SetUpdatedAt(v time.Time) *ProxyAllocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ProxyAllocationUpdateOne) SetProxyID(v int64) *ProxyAllocationUpdateOne {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableProxyID(v *int64) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *ProxyAllocationUpdateOne) AddProxyID(v int64) *ProxyAllocationUpdateOne {
	_u.mutation.AddProxyID(v)
	return _u
}

// SetExternalProviderAccountID sets the "external_provider_account_id" field.
func (_u *ProxyAllocationUpdateOne) SetExternalProviderAccountID(v string) *ProxyAllocationUpdateOne {
	_u.mutation.SetExternalProviderAccountID(v)
	return _u
}

// SetNillableExternalProviderAccountID sets the "external_provider_account_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableExternalProviderAccountID(v *string) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetExternalProviderAccountID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ProxyAllocationUpdateOne) SetAccountID(v int64) *ProxyAllocationUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableAccountID(v *int64) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ProxyAllocationUpdateOne) AddAccountID(v int64) *ProxyAllocationUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ProxyAllocationUpdateOne) ClearAccountID() *ProxyAllocationUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyAllocationUpdateOne) SetRegion(v string) *ProxyAllocationUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableRegion(v *string) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProxyAllocationUpdateOne) ClearRegion() *ProxyAllocationUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetAllocationStatus sets the "allocation_status" field.
func (_u *ProxyAllocationUpdateOne) SetAllocationStatus(v string) *ProxyAllocationUpdateOne {
	_u.mutation.SetAllocationStatus(v)
	return _u
}

// SetNillableAllocationStatus sets the "allocation_status" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableAllocationStatus(v *string) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetAllocationStatus(*v)
	}
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *ProxyAllocationUpdateOne) SetAssignedAt(v time.Time) *ProxyAllocationUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableAssignedAt(v *time.Time) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *ProxyAllocationUpdateOne) ClearAssignedAt() *ProxyAllocationUpdateOne {
	_u.mutation.ClearAssignedAt()
	return _u
}

// SetReleasedAt sets the "released_at" field.
func (_u *ProxyAllocationUpdateOne) SetReleasedAt(v time.Time) *ProxyAllocationUpdateOne {
	_u.mutation.SetReleasedAt(v)
	return _u
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableReleasedAt(v *time.Time) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetReleasedAt(*v)
	}
	return _u
}

// ClearReleasedAt clears the value of the "released_at" field.
func (_u *ProxyAllocationUpdateOne) ClearReleasedAt() *ProxyAllocationUpdateOne {
	_u.mutation.ClearReleasedAt()
	return _u
}

// SetReleaseReason sets the "release_reason" field.
func (_u *ProxyAllocationUpdateOne) SetReleaseReason(v string) *ProxyAllocationUpdateOne {
	_u.mutation.SetReleaseReason(v)
	return _u
}

// SetNillableReleaseReason sets the "release_reason" field if the given value is not nil.
func (_u *ProxyAllocationUpdateOne) SetNillableReleaseReason(v *string) *ProxyAllocationUpdateOne {
	if v != nil {
		_u.SetReleaseReason(*v)
	}
	return _u
}

// ClearReleaseReason clears the value of the "release_reason" field.
func (_u *ProxyAllocationUpdateOne) ClearReleaseReason() *ProxyAllocationUpdateOne {
	_u.mutation.ClearReleaseReason()
	return _u
}

// Mutation returns the ProxyAllocationMutation object of the builder.
func (_u *ProxyAllocationUpdateOne) Mutation() *ProxyAllocationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyAllocationUpdate builder.
func (_u *ProxyAllocationUpdateOne) Where(ps ...predicate.ProxyAllocation) *ProxyAllocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyAllocationUpdateOne) Select(field string, fields ...string) *ProxyAllocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyAllocation entity.
func (_u *ProxyAllocationUpdateOne) Save(ctx context.Context) (*ProxyAllocation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyAllocationUpdateOne) SaveX(ctx context.Context) *ProxyAllocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyAllocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyAllocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyAllocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyallocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyAllocationUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalProviderAccountID(); ok {
		if err := proxyallocation.ExternalProviderAccountIDValidator(v); err != nil {
			return &ValidationError{Name: "external_provider_account_id", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.external_provider_account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxyallocation.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AllocationStatus(); ok {
		if err := proxyallocation.AllocationStatusValidator(v); err != nil {
			return &ValidationError{Name: "allocation_status", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.allocation_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseReason(); ok {
		if err := proxyallocation.ReleaseReasonValidator(v); err != nil {
			return &ValidationError{Name: "release_reason", err: fmt.Errorf(`ent: validator failed for field "ProxyAllocation.release_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyAllocationUpdateOne) sqlSave(ctx context.Context) (_node *ProxyAllocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyallocation.Table, proxyallocation.Columns, sqlgraph.NewFieldSpec(proxyallocation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyAllocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyallocation.FieldID)
		for _, f := range fields {
			if !proxyallocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyallocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyallocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(proxyallocation.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(proxyallocation.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExternalProviderAccountID(); ok {
		_spec.SetField(proxyallocation.FieldExternalProviderAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(proxyallocation.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(proxyallocation.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(proxyallocation.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxyallocation.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(proxyallocation.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.AllocationStatus(); ok {
		_spec.SetField(proxyallocation.FieldAllocationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(proxyallocation.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(proxyallocation.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleasedAt(); ok {
		_spec.SetField(proxyallocation.FieldReleasedAt, field.TypeTime, value)
	}
	if _u.mutation.ReleasedAtCleared() {
		_spec.ClearField(proxyallocation.FieldReleasedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReleaseReason(); ok {
		_spec.SetField(proxyallocation.FieldReleaseReason, field.TypeString, value)
	}
	if _u.mutation.ReleaseReasonCleared() {
		_spec.ClearField(proxyallocation.FieldReleaseReason, field.TypeString)
	}
	_node = &ProxyAllocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyallocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
