// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxyallocation"
)

// ProxyAllocation is the model entity for the ProxyAllocation schema.
type ProxyAllocation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID int64 `json:"proxy_id,omitempty"`
	// ExternalProviderAccountID holds the value of the "external_provider_account_id" field.
	ExternalProviderAccountID string `json:"external_provider_account_id,omitempty"`
	// Sub2API account id; set once the account row exists.
	AccountID *int64 `json:"account_id,omitempty"`
	// Egress region label snapshot (IATA-style, e.g. lax/sgp/nrt).
	Region *string `json:"region,omitempty"`
	// AllocationStatus holds the value of the "allocation_status" field.
	AllocationStatus string `json:"allocation_status,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt *time.Time `json:"assigned_at,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt *time.Time `json:"released_at,omitempty"`
	// ReleaseReason holds the value of the "release_reason" field.
	ReleaseReason *string `json:"release_reason,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyAllocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyallocation.FieldID, proxyallocation.FieldProxyID, proxyallocation.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case proxyallocation.FieldExternalProviderAccountID, proxyallocation.FieldRegion, proxyallocation.FieldAllocationStatus, proxyallocation.FieldReleaseReason:
			values[i] = new(sql.NullString)
		case proxyallocation.FieldCreatedAt, proxyallocation.FieldUpdatedAt, proxyallocation.FieldAssignedAt, proxyallocation.FieldReleasedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyAllocation fields.
func (_m *ProxyAllocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyallocation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxyallocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyallocation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxyallocation.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case proxyallocation.FieldExternalProviderAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_provider_account_id", values[i])
			} else if value.Valid {
				_m.ExternalProviderAccountID = value.String
			}
		case proxyallocation.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case proxyallocation.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = new(string)
				*_m.Region = value.String
			}
		case proxyallocation.FieldAllocationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field allocation_status", values[i])
			} else if value.Valid {
				_m.AllocationStatus = value.String
			}
		case proxyallocation.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = new(time.Time)
				*_m.AssignedAt = value.Time
			}
		case proxyallocation.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				_m.ReleasedAt = new(time.Time)
				*_m.ReleasedAt = value.Time
			}
		case proxyallocation.FieldReleaseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_reason", values[i])
			} else if value.Valid {
				_m.ReleaseReason = new(string)
				*_m.ReleaseReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyAllocation.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyAllocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyAllocation.
// Note that you need to call ProxyAllocation.Unwrap() before calling this method if this ProxyAllocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyAllocation) Update() *ProxyAllocationUpdateOne {
	return NewProxyAllocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyAllocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyAllocation) Unwrap() *ProxyAllocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyAllocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyAllocation) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyAllocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("external_provider_account_id=")
	builder.WriteString(_m.ExternalProviderAccountID)
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Region; v != nil {
		builder.WriteString("region=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("allocation_status=")
	builder.WriteString(_m.AllocationStatus)
	builder.WriteString(", ")
	if v := _m.AssignedAt; v != nil {
		builder.WriteString("assigned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReleaseReason; v != nil {
		builder.WriteString("release_reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ProxyAllocations is a parsable slice of ProxyAllocation.
type ProxyAllocations []*ProxyAllocation
