// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/region"
)

// RegionUpdate is the builder for updating Region entities.
type RegionUpdate struct {
	config
	hooks    []Hook
	mutation *RegionMutation
}

// Where appends a list predicates to the RegionUpdate builder.
func (_u *RegionUpdate) Where(ps ...predicate.Region) *RegionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *RegionUpdate) SetCode(v string) *RegionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableCode(v *string) *RegionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *RegionUpdate) SetNameEn(v string) *RegionUpdate {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableNameEn(v *string) *RegionUpdate {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// SetNameZh sets the "name_zh" field.
func (_u *RegionUpdate) SetNameZh(v string) *RegionUpdate {
	_u.mutation.SetNameZh(v)
	return _u
}

// SetNillableNameZh sets the "name_zh" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableNameZh(v *string) *RegionUpdate {
	if v != nil {
		_u.SetNameZh(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RegionUpdate) SetSortOrder(v int) *RegionUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableSortOrder(v *int) *RegionUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RegionUpdate) AddSortOrder(v int) *RegionUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RegionUpdate) SetEnabled(v bool) *RegionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RegionUpdate) SetNillableEnabled(v *bool) *RegionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegionUpdate) SetUpdatedAt(v time.Time) *RegionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RegionMutation object of the builder.
func (_u *RegionUpdate) Mutation() *RegionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RegionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RegionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := region.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegionUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := region.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Region.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameEn(); ok {
		if err := region.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Region.name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameZh(); ok {
		if err := region.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "name_zh", err: fmt.Errorf(`ent: validator failed for field "Region.name_zh": %w`, err)}
		}
	}
	return nil
}

func (_u *RegionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(region.Table, region.Columns, sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(region.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(region.FieldNameEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameZh(); ok {
		_spec.SetField(region.FieldNameZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(region.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(region.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(region.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(region.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{region.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RegionUpdateOne is the builder for updating a single Region entity.
type RegionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegionMutation
}

// SetCode sets the "code" field.
func (_u *RegionUpdateOne) SetCode(v string) *RegionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableCode(v *string) *RegionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *RegionUpdateOne) SetNameEn(v string) *RegionUpdateOne {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableNameEn(v *string) *RegionUpdateOne {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// SetNameZh sets the "name_zh" field.
func (_u *RegionUpdateOne) SetNameZh(v string) *RegionUpdateOne {
	_u.mutation.SetNameZh(v)
	return _u
}

// SetNillableNameZh sets the "name_zh" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableNameZh(v *string) *RegionUpdateOne {
	if v != nil {
		_u.SetNameZh(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RegionUpdateOne) SetSortOrder(v int) *RegionUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableSortOrder(v *int) *RegionUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RegionUpdateOne) AddSortOrder(v int) *RegionUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RegionUpdateOne) SetEnabled(v bool) *RegionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RegionUpdateOne) SetNillableEnabled(v *bool) *RegionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegionUpdateOne) SetUpdatedAt(v time.Time) *RegionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RegionMutation object of the builder.
func (_u *RegionUpdateOne) Mutation() *RegionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RegionUpdate builder.
func (_u *RegionUpdateOne) Where(ps ...predicate.Region) *RegionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RegionUpdateOne) Select(field string, fields ...string) *RegionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Region entity.
func (_u *RegionUpdateOne) Save(ctx context.Context) (*Region, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegionUpdateOne) SaveX(ctx context.Context) *Region {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RegionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := region.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegionUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := region.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Region.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameEn(); ok {
		if err := region.NameEnValidator(v); err != nil {
			return &ValidationError{Name: "name_en", err: fmt.Errorf(`ent: validator failed for field "Region.name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameZh(); ok {
		if err := region.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "name_zh", err: fmt.Errorf(`ent: validator failed for field "Region.name_zh": %w`, err)}
		}
	}
	return nil
}

func (_u *RegionUpdateOne) sqlSave(ctx context.Context) (_node *Region, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(region.Table, region.Columns, sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Region.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, region.FieldID)
		for _, f := range fields {
			if !region.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != region.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(region.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(region.FieldNameEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameZh(); ok {
		_spec.SetField(region.FieldNameZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(region.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(region.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(region.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(region.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Region{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{region.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
