// Code generated by ent, DO NOT EDIT.

package feedback

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldContent, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldRequestID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldStatus, v))
}

// AdminReply applies equality check predicate on the "admin_reply" field. It's identical to AdminReplyEQ.
func AdminReply(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldAdminReply, v))
}

// RepliedAt applies equality check predicate on the "replied_at" field. It's identical to RepliedAtEQ.
func RepliedAt(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldRepliedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContainsFold(FieldType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContainsFold(FieldContent, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContainsFold(FieldRequestID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContainsFold(FieldStatus, v))
}

// AdminReplyEQ applies the EQ predicate on the "admin_reply" field.
func AdminReplyEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldAdminReply, v))
}

// AdminReplyNEQ applies the NEQ predicate on the "admin_reply" field.
func AdminReplyNEQ(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldAdminReply, v))
}

// AdminReplyIn applies the In predicate on the "admin_reply" field.
func AdminReplyIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldAdminReply, vs...))
}

// AdminReplyNotIn applies the NotIn predicate on the "admin_reply" field.
func AdminReplyNotIn(vs ...string) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldAdminReply, vs...))
}

// AdminReplyGT applies the GT predicate on the "admin_reply" field.
func AdminReplyGT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldAdminReply, v))
}

// AdminReplyGTE applies the GTE predicate on the "admin_reply" field.
func AdminReplyGTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldAdminReply, v))
}

// AdminReplyLT applies the LT predicate on the "admin_reply" field.
func AdminReplyLT(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldAdminReply, v))
}

// AdminReplyLTE applies the LTE predicate on the "admin_reply" field.
func AdminReplyLTE(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldAdminReply, v))
}

// AdminReplyContains applies the Contains predicate on the "admin_reply" field.
func AdminReplyContains(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContains(FieldAdminReply, v))
}

// AdminReplyHasPrefix applies the HasPrefix predicate on the "admin_reply" field.
func AdminReplyHasPrefix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasPrefix(FieldAdminReply, v))
}

// AdminReplyHasSuffix applies the HasSuffix predicate on the "admin_reply" field.
func AdminReplyHasSuffix(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldHasSuffix(FieldAdminReply, v))
}

// AdminReplyIsNil applies the IsNil predicate on the "admin_reply" field.
func AdminReplyIsNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldIsNull(FieldAdminReply))
}

// AdminReplyNotNil applies the NotNil predicate on the "admin_reply" field.
func AdminReplyNotNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldNotNull(FieldAdminReply))
}

// AdminReplyEqualFold applies the EqualFold predicate on the "admin_reply" field.
func AdminReplyEqualFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldEqualFold(FieldAdminReply, v))
}

// AdminReplyContainsFold applies the ContainsFold predicate on the "admin_reply" field.
func AdminReplyContainsFold(v string) predicate.Feedback {
	return predicate.Feedback(sql.FieldContainsFold(FieldAdminReply, v))
}

// RepliedAtEQ applies the EQ predicate on the "replied_at" field.
func RepliedAtEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldRepliedAt, v))
}

// RepliedAtNEQ applies the NEQ predicate on the "replied_at" field.
func RepliedAtNEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldRepliedAt, v))
}

// RepliedAtIn applies the In predicate on the "replied_at" field.
func RepliedAtIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldRepliedAt, vs...))
}

// RepliedAtNotIn applies the NotIn predicate on the "replied_at" field.
func RepliedAtNotIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldRepliedAt, vs...))
}

// RepliedAtGT applies the GT predicate on the "replied_at" field.
func RepliedAtGT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldRepliedAt, v))
}

// RepliedAtGTE applies the GTE predicate on the "replied_at" field.
func RepliedAtGTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldRepliedAt, v))
}

// RepliedAtLT applies the LT predicate on the "replied_at" field.
func RepliedAtLT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldRepliedAt, v))
}

// RepliedAtLTE applies the LTE predicate on the "replied_at" field.
func RepliedAtLTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldRepliedAt, v))
}

// RepliedAtIsNil applies the IsNil predicate on the "replied_at" field.
func RepliedAtIsNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldIsNull(FieldRepliedAt))
}

// RepliedAtNotNil applies the NotNil predicate on the "replied_at" field.
func RepliedAtNotNil() predicate.Feedback {
	return predicate.Feedback(sql.FieldNotNull(FieldRepliedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Feedback {
	return predicate.Feedback(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Feedback) predicate.Feedback {
	return predicate.Feedback(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Feedback) predicate.Feedback {
	return predicate.Feedback(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Feedback) predicate.Feedback {
	return predicate.Feedback(sql.NotPredicates(p))
}
