// Code generated by ent, DO NOT EDIT.

package pricingmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pricingmodel type in the database.
	Label = "pricing_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldModelType holds the string denoting the model_type field in the database.
	FieldModelType = "model_type"
	// FieldUserType holds the string denoting the user_type field in the database.
	FieldUserType = "user_type"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldOfficialInputPrice holds the string denoting the official_input_price field in the database.
	FieldOfficialInputPrice = "official_input_price"
	// FieldOfficialOutputPrice holds the string denoting the official_output_price field in the database.
	FieldOfficialOutputPrice = "official_output_price"
	// FieldImagePricingJSON holds the string denoting the image_pricing_json field in the database.
	FieldImagePricingJSON = "image_pricing_json"
	// FieldSavingPercent holds the string denoting the saving_percent field in the database.
	FieldSavingPercent = "saving_percent"
	// Table holds the table name of the pricingmodel in the database.
	Table = "pricing_models"
)

// Columns holds all SQL columns for pricingmodel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldModel,
	FieldModelType,
	FieldUserType,
	FieldEnabled,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheReadPrice,
	FieldCacheWritePrice,
	FieldOfficialInputPrice,
	FieldOfficialOutputPrice,
	FieldImagePricingJSON,
	FieldSavingPercent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultModelType holds the default value on creation for the "model_type" field.
	DefaultModelType string
	// ModelTypeValidator is a validator for the "model_type" field. It is called by the builders before save.
	ModelTypeValidator func(string) error
	// DefaultUserType holds the default value on creation for the "user_type" field.
	DefaultUserType string
	// UserTypeValidator is a validator for the "user_type" field. It is called by the builders before save.
	UserTypeValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSavingPercent holds the default value on creation for the "saving_percent" field.
	DefaultSavingPercent float64
)

// OrderOption defines the ordering options for the PricingModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByModelType orders the results by the model_type field.
func ByModelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelType, opts...).ToFunc()
}

// ByUserType orders the results by the user_type field.
func ByUserType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByOfficialInputPrice orders the results by the official_input_price field.
func ByOfficialInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfficialInputPrice, opts...).ToFunc()
}

// ByOfficialOutputPrice orders the results by the official_output_price field.
func ByOfficialOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfficialOutputPrice, opts...).ToFunc()
}

// ByImagePricingJSON orders the results by the image_pricing_json field.
func ByImagePricingJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImagePricingJSON, opts...).ToFunc()
}

// BySavingPercent orders the results by the saving_percent field.
func BySavingPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSavingPercent, opts...).ToFunc()
}
