// Code generated by ent, DO NOT EDIT.

package proxyallocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxyallocation type in the database.
	Label = "proxy_allocation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldExternalProviderAccountID holds the string denoting the external_provider_account_id field in the database.
	FieldExternalProviderAccountID = "external_provider_account_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldAllocationStatus holds the string denoting the allocation_status field in the database.
	FieldAllocationStatus = "allocation_status"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// FieldReleasedAt holds the string denoting the released_at field in the database.
	FieldReleasedAt = "released_at"
	// FieldReleaseReason holds the string denoting the release_reason field in the database.
	FieldReleaseReason = "release_reason"
	// Table holds the table name of the proxyallocation in the database.
	Table = "proxy_allocations"
)

// Columns holds all SQL columns for proxyallocation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProxyID,
	FieldExternalProviderAccountID,
	FieldAccountID,
	FieldRegion,
	FieldAllocationStatus,
	FieldAssignedAt,
	FieldReleasedAt,
	FieldReleaseReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ExternalProviderAccountIDValidator is a validator for the "external_provider_account_id" field. It is called by the builders before save.
	ExternalProviderAccountIDValidator func(string) error
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// DefaultAllocationStatus holds the default value on creation for the "allocation_status" field.
	DefaultAllocationStatus string
	// AllocationStatusValidator is a validator for the "allocation_status" field. It is called by the builders before save.
	AllocationStatusValidator func(string) error
	// ReleaseReasonValidator is a validator for the "release_reason" field. It is called by the builders before save.
	ReleaseReasonValidator func(string) error
)

// OrderOption defines the ordering options for the ProxyAllocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByExternalProviderAccountID orders the results by the external_provider_account_id field.
func ByExternalProviderAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalProviderAccountID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByAllocationStatus orders the results by the allocation_status field.
func ByAllocationStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocationStatus, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByReleasedAt orders the results by the released_at field.
func ByReleasedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleasedAt, opts...).ToFunc()
}

// ByReleaseReason orders the results by the release_reason field.
func ByReleaseReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseReason, opts...).ToFunc()
}
