// Code generated by ent, DO NOT EDIT.

package proxyallocation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldProxyID, v))
}

// ExternalProviderAccountID applies equality check predicate on the "external_provider_account_id" field. It's identical to ExternalProviderAccountIDEQ.
func ExternalProviderAccountID(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldExternalProviderAccountID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAccountID, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldRegion, v))
}

// AllocationStatus applies equality check predicate on the "allocation_status" field. It's identical to AllocationStatusEQ.
func AllocationStatus(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAllocationStatus, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAssignedAt, v))
}

// ReleasedAt applies equality check predicate on the "released_at" field. It's identical to ReleasedAtEQ.
func ReleasedAt(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleaseReason applies equality check predicate on the "release_reason" field. It's identical to ReleaseReasonEQ.
func ReleaseReason(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldReleaseReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldProxyID, v))
}

// ExternalProviderAccountIDEQ applies the EQ predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDNEQ applies the NEQ predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDNEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDIn applies the In predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldExternalProviderAccountID, vs...))
}

// ExternalProviderAccountIDNotIn applies the NotIn predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDNotIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldExternalProviderAccountID, vs...))
}

// ExternalProviderAccountIDGT applies the GT predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDGT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDGTE applies the GTE predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDGTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDLT applies the LT predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDLT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDLTE applies the LTE predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDLTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDContains applies the Contains predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDContains(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContains(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDHasPrefix applies the HasPrefix predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDHasPrefix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasPrefix(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDHasSuffix applies the HasSuffix predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDHasSuffix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasSuffix(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDEqualFold applies the EqualFold predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDEqualFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEqualFold(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDContainsFold applies the ContainsFold predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDContainsFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContainsFold(FieldExternalProviderAccountID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotNull(FieldAccountID))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionIsNil applies the IsNil predicate on the "region" field.
func RegionIsNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIsNull(FieldRegion))
}

// RegionNotNil applies the NotNil predicate on the "region" field.
func RegionNotNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotNull(FieldRegion))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContainsFold(FieldRegion, v))
}

// AllocationStatusEQ applies the EQ predicate on the "allocation_status" field.
func AllocationStatusEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAllocationStatus, v))
}

// AllocationStatusNEQ applies the NEQ predicate on the "allocation_status" field.
func AllocationStatusNEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldAllocationStatus, v))
}

// AllocationStatusIn applies the In predicate on the "allocation_status" field.
func AllocationStatusIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldAllocationStatus, vs...))
}

// AllocationStatusNotIn applies the NotIn predicate on the "allocation_status" field.
func AllocationStatusNotIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldAllocationStatus, vs...))
}

// AllocationStatusGT applies the GT predicate on the "allocation_status" field.
func AllocationStatusGT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldAllocationStatus, v))
}

// AllocationStatusGTE applies the GTE predicate on the "allocation_status" field.
func AllocationStatusGTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldAllocationStatus, v))
}

// AllocationStatusLT applies the LT predicate on the "allocation_status" field.
func AllocationStatusLT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldAllocationStatus, v))
}

// AllocationStatusLTE applies the LTE predicate on the "allocation_status" field.
func AllocationStatusLTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldAllocationStatus, v))
}

// AllocationStatusContains applies the Contains predicate on the "allocation_status" field.
func AllocationStatusContains(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContains(FieldAllocationStatus, v))
}

// AllocationStatusHasPrefix applies the HasPrefix predicate on the "allocation_status" field.
func AllocationStatusHasPrefix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasPrefix(FieldAllocationStatus, v))
}

// AllocationStatusHasSuffix applies the HasSuffix predicate on the "allocation_status" field.
func AllocationStatusHasSuffix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasSuffix(FieldAllocationStatus, v))
}

// AllocationStatusEqualFold applies the EqualFold predicate on the "allocation_status" field.
func AllocationStatusEqualFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEqualFold(FieldAllocationStatus, v))
}

// AllocationStatusContainsFold applies the ContainsFold predicate on the "allocation_status" field.
func AllocationStatusContainsFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContainsFold(FieldAllocationStatus, v))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldAssignedAt, v))
}

// AssignedAtIsNil applies the IsNil predicate on the "assigned_at" field.
func AssignedAtIsNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIsNull(FieldAssignedAt))
}

// AssignedAtNotNil applies the NotNil predicate on the "assigned_at" field.
func AssignedAtNotNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotNull(FieldAssignedAt))
}

// ReleasedAtEQ applies the EQ predicate on the "released_at" field.
func ReleasedAtEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldReleasedAt, v))
}

// ReleasedAtNEQ applies the NEQ predicate on the "released_at" field.
func ReleasedAtNEQ(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldReleasedAt, v))
}

// ReleasedAtIn applies the In predicate on the "released_at" field.
func ReleasedAtIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldReleasedAt, vs...))
}

// ReleasedAtNotIn applies the NotIn predicate on the "released_at" field.
func ReleasedAtNotIn(vs ...time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldReleasedAt, vs...))
}

// ReleasedAtGT applies the GT predicate on the "released_at" field.
func ReleasedAtGT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldReleasedAt, v))
}

// ReleasedAtGTE applies the GTE predicate on the "released_at" field.
func ReleasedAtGTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldReleasedAt, v))
}

// ReleasedAtLT applies the LT predicate on the "released_at" field.
func ReleasedAtLT(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldReleasedAt, v))
}

// ReleasedAtLTE applies the LTE predicate on the "released_at" field.
func ReleasedAtLTE(v time.Time) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldReleasedAt, v))
}

// ReleasedAtIsNil applies the IsNil predicate on the "released_at" field.
func ReleasedAtIsNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIsNull(FieldReleasedAt))
}

// ReleasedAtNotNil applies the NotNil predicate on the "released_at" field.
func ReleasedAtNotNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotNull(FieldReleasedAt))
}

// ReleaseReasonEQ applies the EQ predicate on the "release_reason" field.
func ReleaseReasonEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEQ(FieldReleaseReason, v))
}

// ReleaseReasonNEQ applies the NEQ predicate on the "release_reason" field.
func ReleaseReasonNEQ(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNEQ(FieldReleaseReason, v))
}

// ReleaseReasonIn applies the In predicate on the "release_reason" field.
func ReleaseReasonIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIn(FieldReleaseReason, vs...))
}

// ReleaseReasonNotIn applies the NotIn predicate on the "release_reason" field.
func ReleaseReasonNotIn(vs ...string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotIn(FieldReleaseReason, vs...))
}

// ReleaseReasonGT applies the GT predicate on the "release_reason" field.
func ReleaseReasonGT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGT(FieldReleaseReason, v))
}

// ReleaseReasonGTE applies the GTE predicate on the "release_reason" field.
func ReleaseReasonGTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldGTE(FieldReleaseReason, v))
}

// ReleaseReasonLT applies the LT predicate on the "release_reason" field.
func ReleaseReasonLT(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLT(FieldReleaseReason, v))
}

// ReleaseReasonLTE applies the LTE predicate on the "release_reason" field.
func ReleaseReasonLTE(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldLTE(FieldReleaseReason, v))
}

// ReleaseReasonContains applies the Contains predicate on the "release_reason" field.
func ReleaseReasonContains(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContains(FieldReleaseReason, v))
}

// ReleaseReasonHasPrefix applies the HasPrefix predicate on the "release_reason" field.
func ReleaseReasonHasPrefix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasPrefix(FieldReleaseReason, v))
}

// ReleaseReasonHasSuffix applies the HasSuffix predicate on the "release_reason" field.
func ReleaseReasonHasSuffix(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldHasSuffix(FieldReleaseReason, v))
}

// ReleaseReasonIsNil applies the IsNil predicate on the "release_reason" field.
func ReleaseReasonIsNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldIsNull(FieldReleaseReason))
}

// ReleaseReasonNotNil applies the NotNil predicate on the "release_reason" field.
func ReleaseReasonNotNil() predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldNotNull(FieldReleaseReason))
}

// ReleaseReasonEqualFold applies the EqualFold predicate on the "release_reason" field.
func ReleaseReasonEqualFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldEqualFold(FieldReleaseReason, v))
}

// ReleaseReasonContainsFold applies the ContainsFold predicate on the "release_reason" field.
func ReleaseReasonContainsFold(v string) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.FieldContainsFold(FieldReleaseReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyAllocation) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyAllocation) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyAllocation) predicate.ProxyAllocation {
	return predicate.ProxyAllocation(sql.NotPredicates(p))
}
