// Code generated by ent, DO NOT EDIT.

package providerconnectsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExternalProviderAccountID applies equality check predicate on the "external_provider_account_id" field. It's identical to ExternalProviderAccountIDEQ.
func ExternalProviderAccountID(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldExternalProviderAccountID, v))
}

// ProviderType applies equality check predicate on the "provider_type" field. It's identical to ProviderTypeEQ.
func ProviderType(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldProviderType, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldRegion, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldProxyID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldStatus, v))
}

// OauthSessionID applies equality check predicate on the "oauth_session_id" field. It's identical to OauthSessionIDEQ.
func OauthSessionID(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldOauthSessionID, v))
}

// Sub2apiAccountID applies equality check predicate on the "sub2api_account_id" field. It's identical to Sub2apiAccountIDEQ.
func Sub2apiAccountID(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldSub2apiAccountID, v))
}

// CallbackURL applies equality check predicate on the "callback_url" field. It's identical to CallbackURLEQ.
func CallbackURL(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCallbackURL, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// ExternalProviderAccountIDEQ applies the EQ predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDNEQ applies the NEQ predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDIn applies the In predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldExternalProviderAccountID, vs...))
}

// ExternalProviderAccountIDNotIn applies the NotIn predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldExternalProviderAccountID, vs...))
}

// ExternalProviderAccountIDGT applies the GT predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDGTE applies the GTE predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDLT applies the LT predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDLTE applies the LTE predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDContains applies the Contains predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDHasPrefix applies the HasPrefix predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDHasSuffix applies the HasSuffix predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDEqualFold applies the EqualFold predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldExternalProviderAccountID, v))
}

// ExternalProviderAccountIDContainsFold applies the ContainsFold predicate on the "external_provider_account_id" field.
func ExternalProviderAccountIDContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldExternalProviderAccountID, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldProviderType, vs...))
}

// ProviderTypeGT applies the GT predicate on the "provider_type" field.
func ProviderTypeGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldProviderType, v))
}

// ProviderTypeGTE applies the GTE predicate on the "provider_type" field.
func ProviderTypeGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldProviderType, v))
}

// ProviderTypeLT applies the LT predicate on the "provider_type" field.
func ProviderTypeLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldProviderType, v))
}

// ProviderTypeLTE applies the LTE predicate on the "provider_type" field.
func ProviderTypeLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldProviderType, v))
}

// ProviderTypeContains applies the Contains predicate on the "provider_type" field.
func ProviderTypeContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldProviderType, v))
}

// ProviderTypeHasPrefix applies the HasPrefix predicate on the "provider_type" field.
func ProviderTypeHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldProviderType, v))
}

// ProviderTypeHasSuffix applies the HasSuffix predicate on the "provider_type" field.
func ProviderTypeHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldProviderType, v))
}

// ProviderTypeEqualFold applies the EqualFold predicate on the "provider_type" field.
func ProviderTypeEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldProviderType, v))
}

// ProviderTypeContainsFold applies the ContainsFold predicate on the "provider_type" field.
func ProviderTypeContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldProviderType, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionIsNil applies the IsNil predicate on the "region" field.
func RegionIsNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIsNull(FieldRegion))
}

// RegionNotNil applies the NotNil predicate on the "region" field.
func RegionNotNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotNull(FieldRegion))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldRegion, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldProxyID, v))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotNull(FieldProxyID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldStatus, v))
}

// OauthSessionIDEQ applies the EQ predicate on the "oauth_session_id" field.
func OauthSessionIDEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldOauthSessionID, v))
}

// OauthSessionIDNEQ applies the NEQ predicate on the "oauth_session_id" field.
func OauthSessionIDNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldOauthSessionID, v))
}

// OauthSessionIDIn applies the In predicate on the "oauth_session_id" field.
func OauthSessionIDIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldOauthSessionID, vs...))
}

// OauthSessionIDNotIn applies the NotIn predicate on the "oauth_session_id" field.
func OauthSessionIDNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldOauthSessionID, vs...))
}

// OauthSessionIDGT applies the GT predicate on the "oauth_session_id" field.
func OauthSessionIDGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldOauthSessionID, v))
}

// OauthSessionIDGTE applies the GTE predicate on the "oauth_session_id" field.
func OauthSessionIDGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldOauthSessionID, v))
}

// OauthSessionIDLT applies the LT predicate on the "oauth_session_id" field.
func OauthSessionIDLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldOauthSessionID, v))
}

// OauthSessionIDLTE applies the LTE predicate on the "oauth_session_id" field.
func OauthSessionIDLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldOauthSessionID, v))
}

// OauthSessionIDContains applies the Contains predicate on the "oauth_session_id" field.
func OauthSessionIDContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldOauthSessionID, v))
}

// OauthSessionIDHasPrefix applies the HasPrefix predicate on the "oauth_session_id" field.
func OauthSessionIDHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldOauthSessionID, v))
}

// OauthSessionIDHasSuffix applies the HasSuffix predicate on the "oauth_session_id" field.
func OauthSessionIDHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldOauthSessionID, v))
}

// OauthSessionIDIsNil applies the IsNil predicate on the "oauth_session_id" field.
func OauthSessionIDIsNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIsNull(FieldOauthSessionID))
}

// OauthSessionIDNotNil applies the NotNil predicate on the "oauth_session_id" field.
func OauthSessionIDNotNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotNull(FieldOauthSessionID))
}

// OauthSessionIDEqualFold applies the EqualFold predicate on the "oauth_session_id" field.
func OauthSessionIDEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldOauthSessionID, v))
}

// OauthSessionIDContainsFold applies the ContainsFold predicate on the "oauth_session_id" field.
func OauthSessionIDContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldOauthSessionID, v))
}

// Sub2apiAccountIDEQ applies the EQ predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDEQ(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDNEQ applies the NEQ predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDNEQ(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDIn applies the In predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDIn(vs ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldSub2apiAccountID, vs...))
}

// Sub2apiAccountIDNotIn applies the NotIn predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDNotIn(vs ...int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldSub2apiAccountID, vs...))
}

// Sub2apiAccountIDGT applies the GT predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDGT(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDGTE applies the GTE predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDGTE(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDLT applies the LT predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDLT(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDLTE applies the LTE predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDLTE(v int64) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldSub2apiAccountID, v))
}

// Sub2apiAccountIDIsNil applies the IsNil predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDIsNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIsNull(FieldSub2apiAccountID))
}

// Sub2apiAccountIDNotNil applies the NotNil predicate on the "sub2api_account_id" field.
func Sub2apiAccountIDNotNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotNull(FieldSub2apiAccountID))
}

// CallbackURLEQ applies the EQ predicate on the "callback_url" field.
func CallbackURLEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCallbackURL, v))
}

// CallbackURLNEQ applies the NEQ predicate on the "callback_url" field.
func CallbackURLNEQ(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldCallbackURL, v))
}

// CallbackURLIn applies the In predicate on the "callback_url" field.
func CallbackURLIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldCallbackURL, vs...))
}

// CallbackURLNotIn applies the NotIn predicate on the "callback_url" field.
func CallbackURLNotIn(vs ...string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldCallbackURL, vs...))
}

// CallbackURLGT applies the GT predicate on the "callback_url" field.
func CallbackURLGT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldCallbackURL, v))
}

// CallbackURLGTE applies the GTE predicate on the "callback_url" field.
func CallbackURLGTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldCallbackURL, v))
}

// CallbackURLLT applies the LT predicate on the "callback_url" field.
func CallbackURLLT(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldCallbackURL, v))
}

// CallbackURLLTE applies the LTE predicate on the "callback_url" field.
func CallbackURLLTE(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldCallbackURL, v))
}

// CallbackURLContains applies the Contains predicate on the "callback_url" field.
func CallbackURLContains(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContains(FieldCallbackURL, v))
}

// CallbackURLHasPrefix applies the HasPrefix predicate on the "callback_url" field.
func CallbackURLHasPrefix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasPrefix(FieldCallbackURL, v))
}

// CallbackURLHasSuffix applies the HasSuffix predicate on the "callback_url" field.
func CallbackURLHasSuffix(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldHasSuffix(FieldCallbackURL, v))
}

// CallbackURLEqualFold applies the EqualFold predicate on the "callback_url" field.
func CallbackURLEqualFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEqualFold(FieldCallbackURL, v))
}

// CallbackURLContainsFold applies the ContainsFold predicate on the "callback_url" field.
func CallbackURLContainsFold(v string) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldContainsFold(FieldCallbackURL, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldExpiresAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderConnectSession) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderConnectSession) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderConnectSession) predicate.ProviderConnectSession {
	return predicate.ProviderConnectSession(sql.NotPredicates(p))
}
